### ISSUE TITLE
[Discussion] Make Open in Portal more discoverable

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#1057]
To ensure user success for certain Azure Functions tasks, it may be better for us to proactively guide the user towards the next step rather than waiting for them to take action. Open to discussion on whether this should be done as a notification or another pattern available in VS Code. 

Here are some use cases that'll immediately prove valuable:

1. Prompt to create a new function when a new project is created
2. Prompt to publish Application settings after deployment is complete
3. Prompt to "open in the portal" after deployment is complete

/cc @fiveisprime @gbowerman

**Comment by asavaritayal** [comment]
> Is "Open in Portal" a common/important action?

Yes, folks often tend to navigate to the portal to ensure that the functions are showing as expected, to set any secrets / app settings and to view the monitor tab for AI logs

**Comment by EricJizbaMSFT** [comment]
Most of those actions can be done in VS Code. For example "view the monitor tab for AI logs" should be covered by our "Stream Logs" button. We also support listing functions and viewing app settings. I'm open to a discussion on how we make those features more discoverable, but ideally users never have to go to the portal because everything they need is already supported in VS Code.

**Comment by asavaritayal** [comment]
> ideally users never have to go to the portal because everything they need is already supported in VS Code.

Agree on the ideal but I think this is a non-goal for the product since a majority of management tasks are centered around the portal. For example, streaming logs provides a good immediate solution to test a function but most users tend to prefer the monitor tab in the portal for a per function aggregated view of the metrics and options for querying and diagnostics. Similarly, general settings in the portal provides a more exhaustive list of configuration options for things like platform, security, networking, etc. Given that portal is the preferred medium for management tasks, we may want to abstain from replicating these experiences on the client side. Happy to discuss/brainstorm further. 

That said, I think you have the right idea here - maybe "open in portal" doesn't have to be an immediate next step after deployment. Instead, we can work on making it more visible through the extension.

**Comment by EricJizbaMSFT** [comment]
As mentioned above, we already have an issue for your first bullet point. I've created a separate issue to track your second bullet point since there's no debate there either: https://github.com/Microsoft/vscode-azurefunctions/issues/1077. And I figure we can repurpose this issue to continue discussing Open In Portal

I didn't mean to imply we would replace the portal. I think the portal is always going to be more exhaustive for management tasks, etc. and I don't want to replicate that. I do want to keep people in VS Code for the entire "happy path" scenario, and I consider "post-deploy" to be part of the "happy path".

**Comment by jinglouMSFT** [comment]
We will keep monitoring user feedback and telemetry to see if there is a need to make "Open in Portal" more discoverable. But for now, it's a lower priority comparing to other asks and tasks on hand. Closing the issue for now.
