### ISSUE TITLE
Support "Start Without Debugging"

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#1064]
Repro steps:
1. 'ctrl'+F5 or select "Start Without Debugging" from the command palette

Expected:
It starts the func host, but doesn't attach

Actual:
It starts the func host and does all the debug stuff

_Originally brought up here by @nzthiago: https://github.com/Microsoft/vscode-azurefunctions/issues/721_

**Comment by malthe** [comment]
The problem is that invariably, either action cleans, builds and starts the function in the `Debug` configuration.

For "Start without debugging", the task that eventually runs is what matches on `$func-watch`. When you create a function, this is what's being set up in `tasks.json` (excerpt):
```json
{
      "type": "func",
      "dependsOn": "build",
      "options": {
        "cwd": "${workspaceFolder}/bin/Debug/netcoreapp2.1"
      },
      "command": "host start",
      "isBackground": true,
      "problemMatcher": "$func-watch"
    }
```
For the "Start without debugging" action, this should be `Release` (and the build commands that precede it need to target this configuration).
