### ISSUE TITLE
Miss "(Read only)" next to "Functions/Proxies" node for a new Linux Function App

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1129]
**OS**: All
**Build Version**: [20190327.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4473)
**Regression:** Not a Regression

**Repro Steps:**
1. Set "azureFunctions.advancedCreation" to true.
2. Create a new Linux Function App.
3. Expand the new Linux Function App and check the result.

**Expect:**
Display "(Read only)" next to "Functions/Proxies" nodes like in Azure Portal.

**Actual:**
Miss "(Read only)" next to "Functions/Proxies" nodes.
![image](https://user-images.githubusercontent.com/34729092/55071395-bf106900-5045-11e9-8336-c9c86a04febe.png)

**More Info:**
Display  "(Read only)" next to "Functions" node after deploying a project to it.
![image](https://user-images.githubusercontent.com/34729092/55071427-d3ecfc80-5045-11e9-8542-8d1b3a10e62c.png)

**Comment by EricJizbaMSFT** [comment]
We know it's read-only based on the app setting `WEBSITE_RUN_FROM_ZIP` or `WEBSITE_RUN_FROM_PACKAGE` and that setting doesn't exist until you deploy for the first time to a linux consumption app.

Closing this as won't-fix since it would require a special case just to handle and it isn't worth it. The "read-only" mode prevents them from trying to delete functions, but you can't delete functions anyways if you've never deployed

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
