### ISSUE TITLE
Improve experience when can't retrieve templates

### ISSUE THREAD

**Issue by Miggleness** [microsoft/vscode-azurefunctions#1145]
Repro steps:
1. Created a new functions project using template release 2.18.5 by running `dotnet new func -n Durable1`

2. Installed Azure functions extension `0.16.0`

3. Updated Durable1.csproj and set target framework from `netcoreapp2.1` to `netcoreapp2.2`

4. Updated Microsoft.NET.Sdk.Functions to `1.0.26`

5. Ran `dotnet restore`

6. Added function using Azure Functions extensions to my Durable project.  The VS Code specific files were generated but no function file was created.  I've no problem with my internet connection

----------------
1.2.Action: azureFunctions.createFunctionError type: ErrorError Message: There was an error in retrieving the templates.  Recheck your internet connection and try again.Version: 0.16.0OS: darwinVS Code Version: 1.32.3<details><summary>Call Stack</summary>```TemplateProvider.<anonymous> (dist/extension.bundle.js:1:527582)Generator.next (<anonymous>)module.exports.n (dist/extension.bundle.js:1:527045)new module.exports.t.exports (dist/extension.js:126:25776)module.exports.n (dist/extension.bundle.js:1:526822)TemplateProvider.getTemplates (dist/extension.bundle.js:1:527507)FunctionListStep.<anonymous> (dist/extension.bundle.js:172:116401)Generator.next (<anonymous>)o (dist/extension.bundle.js:172:113286)i (dist/extension.js:126:21877)dist/extension.js:126:22221```</details>

**Comment by EricJizbaMSFT** [comment]
@Miggleness are there any logs in the "Azure Functions" section of the output window?
![Screen Shot 2019-04-01 at 10 54 09 AM](https://user-images.githubusercontent.com/11282622/55348632-7ead5280-546c-11e9-8f1e-3538b885f96a.png)

**Comment by Miggleness** [comment]
I'll send the logs over tonight.

**Comment by EricJizbaMSFT** [comment]
Removed the "needs more info" label as I think we need to look into this more even if we don't get the logs (although they would be helpful @Miggleness if you can still repro!).

For example, I think "Recheck your internet connection" isn't the best advice since we have backup templates shipped with the extension that shouldn't need the internet. For C#, the likely culprit is a configuration of the dotnet cli that doesn't work with us for some reason.

As another idea - I've been thinking about adding a timeout to `tryGetCliFeedJson`. If it doesn't work in a few seconds, we should probably fall back to cached or backup templates.

**Comment by Miggleness** [comment]
Apologize I hadn't been as helpful as I should've been.  I need to re-setup my machine and try this with the latest version of everything as that makes more sense.

**Comment by Miggleness** [comment]
Repeated the steps, this time with the following versions and worked fine.  Since the objective of this issue has transcended the reported issue, I won't mark this one as closed just yet.

VS Code Azure Functions Extension `0.17.0`
Template `2.20.2`
