### ISSUE TITLE
Error 403 when deploying Function App from VS Code 

### ISSUE THREAD

**Issue by cathornton** [Microsoft/vscode-azurefunctions#1150]
When I hit the Up Arrow (Deploy to Function App...) from the Azure Functions Extension for VS Code, select "Create New Function App in Azure", provide a unique name, then  every time I get an error in the notification box that says 'Failed with code "403".'
My permissions should be OK, because I can manually create that Function App in the Portal using the same account.
I have tried this on 2 PCs now, with the same outcome both times.  I have also tried publishing to another Azure subscription and get the same issue.

Repro steps:1.2.Action: azureFunctions.deploy
Error type: 403 
Error Message: Failed with code 403.
Version: 0.16.0
OS: win32
VS Code Version: 1.32.3<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment]
@cathornton 
1. What type of project are you deploying? Python or a different language?
1. Does it work if you select an existing function app in azure instead of creating a new one from VS Code?

We have a number of defaults when creating a function app and you can manually enter those by setting `azureFunctions.advancedCreation` to `true` in your VS Code settings. There could be a default that might not work for you and trying that would help us figure out which default that is.
