### ISSUE TITLE
Not seeing any templates listed

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#117]
Repro:
1. Create new Function App
1. Select "JavaScript"
1. After it initializes, select "Create Function"
1. Select directory just initialized
1. See the following:

<img width="798" alt="no templates" src="https://user-images.githubusercontent.com/7132626/33645896-022ad48e-da02-11e7-9b1b-f052c0e8dd79.png">

**Comment by fiveisprime** [comment]
Looks like the template names in the API were changed. :( It's failing because there are no matches for "verified" templates (e.g. "BlobTrigger" changed to "Blob Trigger").

A quick workaround if you still want to test is to add `"azureFunctions.templateFilter": "All"` to your config, That will make all of the templates show up.

**Comment by EricJizbaMSFT** [comment]
@jeffhollan thanks for filing the issue! We've published an [update](https://github.com/Microsoft/vscode-azurefunctions/releases/tag/v0.3.1) to the extension that fixes this bug and reduces the risk of similar bugs occurring in the future

That being said, you're more than welcome to continue using the 'All' category in your user settings.
