### ISSUE TITLE
Deployment fails when VSCode locks @types

### ISSUE THREAD

**Issue by altano** [Microsoft/vscode-azurefunctions#1185]
# Repro steps:
1. Create a TypeScript Azure Function in VSCode
1. Install a bunch of @types, import them into some .ts files
1. While those .ts files are open in VSCode, try to deploy the app

During the `npm prune` step the deployment will fail because VSCode has locked the types files in the node_modules directory. The error varies but it's also something `EPERM` related.

# Workaround 1
Restart VSCode, don't open any TS files, try to deploy the app again. Either because I haven't opened TS files yet or because I'm doing it so quickly and TSC hasn't run yet, VSCode doesn't have a chance to lock the @type files, so the npm prune and deploy succeed.

# Workaround 2
Move all my TS dependencies (e.g. @types and typescript itself) from devDependencies to regular dependencies and deploy them to Azure. If they aren't part of the prune the deploy will succeed.

# Details
Action: azureFunctions.deploy
Error type: `EPERM`
Error Message: `EPERM: operation not permitted, scandir 'c:\src\...\node_modules\@types'`
Version: 0.16.0
OS: win32
VS Code Version: 1.33.1

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - this is a known issue tracked by https://github.com/Microsoft/vscode-azurefunctions/issues/1105. It's actually caused by an upstream issue in TypeScript tracked here: https://github.com/Microsoft/TypeScript/issues/29407

A few more workarounds you can try:
1. Modify the `azureFunctions.preDeployTask` setting from `prune` to `build`. This has the same effect as your Workaround 2, but might be a little cleaner/easier to change back
1. Restart the ts server before deploying:
![image](https://user-images.githubusercontent.com/2193314/56051455-850cbb80-5d03-11e9-969d-67dcb4b46176.png)
