### ISSUE TITLE
Local debug is not working

### ISSUE THREAD

**Issue by jjindrich** [Microsoft/vscode-azurefunctions#123]
I tried to debug locally my JavaScript code. 
But I'm getting error: 
> Executing task: func host start <
This requires dotnet cli to be on the path. Make sure to install .NET Core SDK 2.0 https://www.microsoft.com/net/core
Terminal will be reused by tasks, press any key to close it.

But I installed everything required - dotnet core, sdk, azure cli sdk
I checked from command prompt to run function, is running successfully.

**Comment by EricJizbaMSFT** [comment]
@jjindrich so it works from the command line, but not when you debug in VS Code? If you haven't already, try restarting VS Code (if you installed dot net core while VS Code was open - it won't pick up your updated 'PATH' variable)

Can you run `func host start` from VS Code's integrated terminal? If not, VS Code isn't picking up your environment variables for some reason. If it's working from the command prompt - you should be able to open VS Code from there (aka run `code .` to open the current folder) and it should exactly clone your environment variables from that prompt

**Comment by jjindrich** [comment]
I checked following:
1. running func host start is working from command line
2. started code from command line - debug not working
3. manually executed func host start in code terminal is working

**Comment by EricJizbaMSFT** [comment]
@jjindrich sorry a lot of us were OOF around the holiday time. Our extension creates a `.vscode/launch.json` and `.vscode/tasks.json` file for you when you create a new project, but when you debug it's using the generic VS Code tasks system and Node debugger. I don't know why you're getting that error and I think it would be better to file an issue on the [VS Code Repo](https://github.com/Microsoft/vscode) since we don't control that part of the experience.

You can also try editing your `.vscode\tasks.json` file and replacing `func host start` with `dotnet --version`. That might help us figure out if it's an issue in the vs code task system or if it's an issue with the functions cli. This is my output:
```
> Executing task: dotnet --version <

2.0.0

Terminal will be reused by tasks, press any key to close it.
```

Closing this issue as I don't think we can fix in this repository.
