### ISSUE TITLE
Trying to deploy an app that works perfectly on local but getting the error on VS CODE

### ISSUE THREAD

**Issue by anindya5** [microsoft/vscode-azurefunctions#1301]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/adey1/Documents/GitHub/HTM_integration/AzureFunctionBatch/AzureFunctionBatch.zip

Version: 0.17.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

</details>

**Comment by EricJizbaMSFT** [comment]
Based on the discussion in https://github.com/microsoft/vscode-azurefunctions/issues/1303, it sounds like this happens when you select "Deploy Anyway" after "func pack" fails. That task is the one creating the zip file, so I think the error here makes sense if that task fails. I'm going to close this issue, but try my suggestion listed in the other issue. I'll leave that one open until you confirm if that works or not
