### ISSUE TITLE
Deploying Azure Function from Code returns timeout

### ISSUE THREAD

**Issue by arheom** [microsoft/vscode-azurefunctions#1321]
Repro steps:
- Create Azure functions (Node.je, Linux based) using Visual Studio Code Azure Functions extension
- Deploy to Azure using same extensions
- All steps work well, until the Syncing triggers step, which returns the following exception:

Action: azureFunctions.deploy
Error type: GatewayTimeout
Error Message: The gateway did not receive a response from 'Microsoft.Web' within the specified time period.

Version: 0.13.1
OS: win32

It worked 2-3 times, but 90% of the time it does not work, so the code should be correct.

Any idea how to workaround the issue or solve it?

Thanks!

**Comment by EricJizbaMSFT** [comment]
@arheom were these failures all around the same time? There could've been an outage in Azure. Maybe try deploying to a different region? Also - were you deploying to Linux Consumption? That's still in preview, so that might be part of the problem.

I haven't seen the `GatewayTimeout` error before - is there anything particularly unique about your project?
