### ISSUE TITLE
Azure Functions extension throws an error trying to create a new project

### ISSUE THREAD

**Issue by abrinckm** [microsoft/vscode-azurefunctions#1324]
I'm following the documentation here:
https://azure.microsoft.com/en-us/resources/samples/app-service-web-dotnet-manage/

Initially, I would get the error 'MSBUILD Failed: Specify a project or solution file'. I solved that much at least by creating a new project in VS Code Azure Functions extension.

Repro steps:
 
Just follow the steps in the tutorial:

1.  `git clone https://github.com/Azure-Samples/app-service-web-dotnet-manage.git`
2.  `cd app-service-web-dotnet-manage`
3.  code . (open VS Code)

(This is not in the tutorial but this step is necessary to run `dotnet restore`)
4.  Create a new project 
      1. Choose C# 
      2. Choose 'Skip for new' for template

Action: azureFunctions.createNewProject
Error type: Error
Error Message: The version in your tasks.json must be "2.0.0" to work with Azure Functions.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
DotnetInitVSCodeStep.<anonymous> extension.bundle.js:1:735389
module.exports.n extension.bundle.js:1:733853
module.exports.n extension.bundle.js:1:733630
DotnetInitVSCodeStep.writeTasksJson extension.bundle.js:1:735149
DotnetInitVSCodeStep.<anonymous> extension.bundle.js:1:734559
o extension.bundle.js:1:733686
```

</details>

**Comment by EricJizbaMSFT** [comment]
@abrinckm the [tasks](https://github.com/Azure-Samples/app-service-web-dotnet-manage/blob/master/.vscode/tasks.json) in that example are using version "0.1.0", which has been deprecated in VS Code. We don't work with that version of the tasks. You could honestly just delete the `.vscode/tasks.json` file because it doesn't look like it does much.

Also - if you create a function project in that folder - it would overwrite some of the sample stuff I think. Not sure how you plan to use both that project and a function project

**Comment by abrinckm** [comment]
Thanks for the quick response! I'm trying to learn .NET and Azure Functions simultaneously. I think this can be closed. I created my own function project as a starting point since the sample project was outdated. So far no errors or issues from this extension.
