### ISSUE TITLE
Integrate: 'Event Hub connection' field not populated upon deployment

### ISSUE THREAD

**Issue by deathgaze** [microsoft/vscode-azurefunctions#1326]
For Event Hub triggers, this is causing deployment via the IDE to break the application. Stuff that works fine on my local is now failing to trigger properly when deployed.

Am I missing something or am I supposed to fill this out again in the Azure UI?

**Comment by EricJizbaMSFT** [comment]
@deathgaze after deploying, you should see a dialog with a button that says "Upload Settings". That will upload the event hub connection from your local.settings.json file to Azure. You can also right click on the "Application Settings" node in the Azure Functions view and select "Upload Settings".

This doesn't happen automatically because a lot of people might be running against different storage accounts/event hubs when running locally and don't want to overwrite the settings that are used when running in Azure.
