### ISSUE TITLE
Prompt for OS in basic-create mode if no project is open

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1330]
Right-click on a subscription in VS Code Azure Functions list, and it defaults to Windows view - providing a runtime selection of JavaScript, .NET, Java, PowerShell. You have to turn on "Advanced creation" to see Python under Linux -< consumption. 
Eliminate this distinction.
Azure Functions 0.17.1 (Windows)
![VSCode-functions](https://user-images.githubusercontent.com/4258913/59138093-d91cd080-893f-11e9-9438-d8e69db265e0.png)

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/1317

I'm okay prompting for OS in basic create mode if you don't have a project open. @fiveisprime you fine with that? In the past we didn't do it because Linux was still in preview and based on telemetry the majority of users have a project open when creating a function app anyways.

That being said, I do _not_ think we should prompt for OS if the user has a project open. This is relevant for JavaScript and .NET, which technically support both OS's. Linux is still in preview and basic create is supposed to have as few prompts as possible.

**Comment by fiveisprime** [comment]
Yeah, I'm fine with that.
