### ISSUE TITLE
Node 12

### ISSUE THREAD

**Issue by mikeerickson** [microsoft/vscode-azurefunctions#1352]
I am trying to join the Azure Functions bandwagon, using the Microsoft tutorial.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code

When running, the server dies stating the runtime requires an LTS-covered version, however, I am using Node 12.2

```bash
[error] Incompatible Node.js version. The version you are using is v12.2.0, but the runtime requires an LTS-covered major version (ex: 8.11.1 or 10.14.1). LTS-covered versions have an even major version number (8.x, 10.x, etc.) as per https://github.com/nodejs/Release#release-plan. For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, install or switch to a supported node version (make sure to quit and restart your code editor to pick up the changes)
```

Is there some way to "change" this require so that I can test with the version of Node I am using, or must I downgrade to the supported version range.

Alternatively, is there a way to get this running against a Docker image which has the desired Node version?

**Comment by EricJizbaMSFT** [comment]
@mikeerickson It's possible the func cli doesn't support Node 12 yet.

> Alternatively, is there a way to get this running against a Docker image which has the desired Node version?

You could try the [remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. After you install that extension, open the command palette (view -> command palette) to create a container configuration file for functions from a basic Node template:
<img width="383" alt="Screen Shot 2019-06-21 at 3 50 05 PM" src="https://user-images.githubusercontent.com/11282622/59950741-6b42cf80-943c-11e9-9fad-6cbbde1157a2.png">
<img width="457" alt="Screen Shot 2019-06-21 at 3 50 23 PM" src="https://user-images.githubusercontent.com/11282622/59950742-6bdb6600-943c-11e9-9721-b7c5ce227375.png">

You can modify the "Dockerfile" in the `.devcontainer` folder if you want, but otherwise just click "Reopen" when you see a notification like this:
<img width="459" alt="Screen Shot 2019-06-21 at 3 57 50 PM" src="https://user-images.githubusercontent.com/11282622/59951077-6e8a8b00-943d-11e9-9224-7c6151c143ec.png">

The Remote Containers extension is pretty new so let us know if you notice any problems (especially as it relates to the functions extension), but I've tried it a few times and it's worked well for me
