### ISSUE TITLE
"appsettings.json" is an old file name and is deprecated.

### ISSUE THREAD

**Issue by jwisener** [microsoft/vscode-azurefunctions#1365]
I don't understand below why you say, "old", it's confusing coming from writing .net core api applications where we use appsettings.{environment}.json files quite heavily. 

Trying to move into azure functions V2 and capitalize on our existing .net core work is proving quite challenging. The documentation on how to properly do this is not well defined and seems to be contradictory. We can't use our strongly created classes because there is no way in the the startup to configure and bind the settings to a strongly typed class as we have done in many .net core api applications. That combined with the fact for every environment (prod, dev, staging, testing) x 5+ applications now we have to go into every web application via the portal and manually set up over 25+ different app settings for each application.  In .net core we were able to only set the only the very sensitive settings in the portal, but many were not sensitive (such as a api endpoint to 3rd party for data consummation, etc) and it was fine for those to live in the appsettings.{environment}.json file (yes the alot of the settings change from env to env). So I guess a couple of questions, 1. Where is the documentation on how this officially works with V2?  2. Is it possible to upload the settings via file in the portal, if we have to do this by hand.

"appsettings.json" is an old file name and is deprecated. See [here](https://github.com/Azure/azure-functions-core-tools/issues/122) for more info. Please use "local.settings.json" file going forward. I think they're pretty much the same format/usage, but see [here](https://docs.microsoft.com/azure/azure-functions/functions-run-local#local-settings-file) for more info on local.settings.json.

We have an [existing bug](https://github.com/Microsoft/vscode-azurefunctions/issues/324) where 'download' doesn't work if you don't have a local.settings.json file, but the easy workaround is to create the file before you download.

_Originally posted by @EricJizbaMSFT in https://github.com/microsoft/vscode-azurefunctions/issues/327#issuecomment-382131099_

**Comment by EricJizbaMSFT** [comment]
I don't think it's possible in the portal, but you can upload settings through VS Code:
![Screen Shot 2019-07-02 at 3 16 28 PM](https://user-images.githubusercontent.com/11282622/60550304-6273b880-9cdc-11e9-808e-e7c8a91b23f2.png)

The docs for local settings are here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file. This repo is specifically for the VS Code extension and I can help with that, but otherwise I would recommend following these instructions to get more generic help for Azure Functions: https://github.com/Azure/Azure-Functions#questions--help
