### ISSUE TITLE
Unable to deploy azure function (Python)

### ISSUE THREAD

**Issue by mateuszgalganekbbraun** [microsoft/vscode-azurefunctions#1409]
Repro steps:

1. Create Python Azure function in VSC 
2. Deploy from VSC

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\galgmapl\Projekty\AzReports\AzReports.zip

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:5208
o extension.bundle.js:332:4796
```

Addational output from console:
```
> Executing task: .env\Scripts\activate ; func pack <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Error: unknown argument pack
Azure Functions Core Tools (1.0.15)
Function Runtime Version: 1.0.11959.0

```
</details>

**Comment by EricJizbaMSFT** [comment]
@mateuszgalganekbbraun this error happens most often if the "func pack" task failed. Check to see if that task failed and address any errors that it reported

**Comment by mateuszgalganekbbraun** [comment]
Thatnks for response.
I don't have task `pack`

**Comment by EricJizbaMSFT** [comment]
@mateuszgalganekbbraun it's set by default in your settings.json. You should see `azureFunctions.preDeployTask` set to `func: pack`. In any case, just let me know all of the errors that happen when you try to deploy. I'm guessing it'll say that the "func: pack" task failed and you'll be given an option to "Deploy Anyway". Instead of deploying, take a look at the output window for the func pack task

**Comment by EricJizbaMSFT** [comment]
@pranavmody not sure what the problem is. If there's an error when running func pack - it's likely in the func cli, not in VS Code.

On a related note, we've got some [stuff](https://github.com/microsoft/vscode-azurefunctions/pull/1420) in the works to eliminate the need for the func pack task completely. Hopefully that will get out soon and solve your issue

**Comment by anjana006** [comment]
I'm new to azure and not sure If this is the right place to post my question. But, I get the same error and I'm not getting any solutions for it.

I have added just one package, "**tweepy == 3.8.0**" in my **requirements.txt** and it seems like it is crashing right during it's installation during deployment, And the **PySocks** package is probably just a dependency for tweepy (shown in the image)

I have no such issues when the debug it locally. 

How can I resolve this deployment issue?

![err](https://user-images.githubusercontent.com/23037023/64737807-bad4ec80-d4bb-11e9-925a-6ee26cb2f8f5.PNG)
