### ISSUE TITLE
Local debug not working

### ISSUE THREAD

**Issue by kktam** [Microsoft/vscode-azurefunctions#142]
The error message on the Terminal is

```
> Executing task: func host start <

'func' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Versions:
node - v8.9.0
dot not core - 2.1.2
VS Code 1.19.1
Windows 7

**Comment by EricJizbaMSFT** [comment]
Please install the [Azure Core Function Tools 2.0](https://www.npmjs.com/package/azure-functions-core-tools):
```
npm install --global azure-functions-core-tools@core
```

Unfortunately our extension doesn't directly control the error message you're seeing above (otherwise we could make it clearer), but we do have the prerequisite listed in a few places:
https://github.com/Microsoft/vscode-azurefunctions#prerequisites
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions

Feel free to re-open this if that doesn't work for you
