### ISSUE TITLE
What I can do?

### ISSUE THREAD

**Issue by Sushytska** [microsoft/vscode-azurefunctions#1516]
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet '/home/valli/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.18.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg' --require '/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg' --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name 'Azure' --arg:AzureFunctionsVersion v2" failed with exit code "255":
Error: Couldn't find item to install: "/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg".
Error: Couldn't find item to install: "/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg".
ERROR: Failed to find template with identity "Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x".

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:135730
o extension.bundle.js:1:134668
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Sushytska does this consistently repro? What happens if you reload VS Code? Also could you check those paths to see if they exist:

/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~2.nupkg

/home/valli/.config/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~2.nupkg
