### ISSUE TITLE
[Discussion] Order of nodes under a function app

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1607]
**OS:** Win10 & Mac
**Build Version**: [20191021.4](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11416)
**Regression:** Previous Release

**Repro Steps:**
1. Create a new function app --> Expand it.
2. Check the list nodes.

**Expect:**
All nodes are list in alphabetical order.

**Actual:**
Not all nodes are list in alphabetical order.
![image](https://user-images.githubusercontent.com/34729092/67267256-7f7b0400-f4e4-11e9-8c47-1b3b23f09220.png)

**Comment by EricJizbaMSFT** [comment]
@fiveisprime I changed this when I added Files and Logs. Seems better to have an opinionated order rather than purely alphabetical. Here's what alphabetical looks like:
![Screen Shot 2019-10-22 at 1 40 49 PM](https://user-images.githubusercontent.com/11282622/67330736-ada31880-f4d1-11e9-80c1-6b436d8ea63e.png)
(Side note: need to update "read only" casing to be consistent)

I feel like "Functions" should be first because it seems the most useful and I like having "Logs" and "Files" next to each other, but otherwise no strong preference. What do you think?

Here's the order in the portal:
![Screen Shot 2019-10-22 at 1 43 26 PM](https://user-images.githubusercontent.com/11282622/67331022-1d190800-f4d2-11e9-9401-4605df452778.png)

**Comment by fiveisprime** [comment]
I really like the current ordering. Functions and App Settings should definitely go together, proxies and slots last because they are least used.

I say leave it as it.

**Comment by v-dantch** [comment]
Got it. Thanks for your quick response and share. And we will update it in our side.
