### ISSUE TITLE
azure function deploy python runtime, internal server error

### ISSUE THREAD

**Issue by moneysqtw** [microsoft/vscode-azurefunctions#1657]
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.pipeline extension.bundle.js:218:2797983
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:636475
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
@moneysqtw unfortunately this error happens somewhat often from Azure and it could be caused by a variety of things. We'll need much more info to help diagnose, for example:
1. Does it happen consistently?
1. What region?
1. What plan type (consumption/premium/etc.)
1. Is this a brand new project?
1. What type of triggers do the project have?
