### ISSUE TITLE
Update v3 tag when installing with brew

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#1738]
**OS:** Mac
**Build Version:** [20191205.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12893)

**Repro Steps:**
1. F1 -> Type and select "Azure Functions: Uninstall Azure Functions Core Tools".
2. F1 -> Type and select "Azure Functions: Install or Update Azure Functions Core Tools"->Select "Azure Functions v3 Preview".
3. Check the Azure Functions output.

**Expect:**
Succeed to install v3 func cli without any errors.

**Actual:**
Fail to install v3 func cli with errors.
![image](https://user-images.githubusercontent.com/45614674/70312045-c97a3800-184d-11ea-8fc9-2421e12696b6.png)

**Comment by v-ruizh** [comment]
This issue does not reproduce on Azure Functions extension [20191230.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13361&view=results), close it.

**Comment by EricJizbaMSFT** [comment]
I'm actually going to re-open this one. We followed up offline with the functions team and they added the "preview" tag back for brew, but we still need to update to the non-preview tag. New tags are listed here: https://github.com/Azure/homebrew-functions/tree/master/Formula

I believe we need to do `azure-functions-core-tools@3` instead of `azure-functions-core-tools-v3-preview`. (as shown in the output window)
