### ISSUE TITLE
Mac: Code Helper (Renderer) wants to use your confidential information

### ISSUE THREAD

**Issue by foucdeg** [microsoft/vscode-azurefunctions#1759]
Since recently, when I open VS Code with my usual extensions, I get a system password prompt with the following message:

> Code Helper (Renderer) wants to use your confidential information stored in "VS Code Azure" in Keychain.

This thread https://github.com/microsoft/vscode/issues/84932#issuecomment-554865071 had me disable my extensions one by one until I was able to single out the Azure Functions extension. When it is disabled, the behaviour doesn't happen. This is new behaviour (I've used the extensions since June and the issue happened two weeks ago).

How can I avoid this password prompt?

**Comment by EricJizbaMSFT** [comment]
The Azure Account extension uses keychain on Mac to store login information, which is probably why you're getting prompted. Are you signed in to Azure? Did you update your OS a few weeks ago? I feel like I've heard the lastest Mac OS might've changed something. To fix the root cause, you'd probably need to file an issue on the account extension directly: https://github.com/microsoft/vscode-azure-account

From the Functions extension, we might be able to mitigate the issue by delaying our request to get account info until absolutely necessary (resulting in fewer prompts). Would need further investigation.

**Comment by foucdeg** [comment]
Thanks @EricJizbaMSFT , I did update MacOS recently. Will file an issue on the other repo.

**Comment by EricJizbaMSFT** [comment]
Looked into this an there's not much we can do to delay loading credentials. The Azure Account extension does it on activation and it'll always activate when we activate since it's our dependency. Seems like "Always Allow" alleviated the annoyance of the prompt anyways
