### ISSUE TITLE
It will skip the step "select an OS" during creating basic Function App if open a project in advance

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#1771]
**OS:** All
**Build Version:** [20191226.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13327&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Open a project in VS Code.
2. F1 --> Select "Azure Functions: Create Function App in Azure...".
3. Enter an unique name for this function app.

**Expect:**
"Select an OS" option pops up.
![image](https://user-images.githubusercontent.com/57662131/71509958-1fc81d00-28c8-11ea-92de-b8d965dcfad9.png)

**Actual:**
It will skip the step "select an OS" and pop up "select a runtime" directly.

**More Info:**
1. This issue does not reproduce during creating advanced Function App.
2. It will skip the step "select an OS" and "select a runtime" if open a C#/PowerShell project in advance.

**Comment by EricJizbaMSFT** [comment]
@v-xinda this is by design. For "Basic" create we want to default as many choices as we can for the user, including OS. For "Advanced" create, we will prompt them for everything. 

In addition, we documented this here: https://github.com/microsoft/vscode-azurefunctions/wiki/Create-Function-App-defaults

**Comment by v-xinda** [comment]
Got it. Thanks for your sharing.
