### ISSUE TITLE
Use better description text in create function quickpick's text box

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1787]
In the create function QuickPick:

![2020-01-13_16-55-35](https://user-images.githubusercontent.com/1898161/72341001-83748780-36c9-11ea-8e75-15c10b873e0e.png)

don't use the template name ("HTTPTrigger") as the text boxes description since the QuickPick's title already shows the template name in the title.

I suggest to use "function name" or at least a modification of the template name in the description instead.

The doc on https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-02 even warns about using the template's name because its confusing.

**Comment by EricJizbaMSFT** [comment]
We see the confusion here, but had trouble deciding on a different name. Closest we came was just to add a "1" to make it more clear it's an instance of an http trigger

**Comment by nigarfin** [comment]
What about following a schema like:

- HTTP Trigger -> HttpFunction
-Blob Trigger -> BlobFunction
etc...

**Comment by kraigb** [comment]
In the docs that @weinand refer to, I used "HttpExample" specifically to have a unique name in the whole conversation. That is when the function is named the same as the trigger, you have to qualify every reference to "HttpTrigger" by stating whether you're talking about the trigger or the function itself. That adds unnecessary confusion, and it originates with a poor choice of default name for the code function in the template.

I highly recommend NOT using anything containing "Function" because there are already too many "functions" floating around in this context: the function you write in code," Azure Functions," the "functions project" on your local machine, and the "functions app" on Azure. It's already difficult enough to keep those straight.

Something like HttpExample also implies that one should rename it to something more meaningful. For Http you could use HttpEndpoint1 or something like that, but I don't know if that pattern holds well for other triggers. "Example" I think is universal enough.

**Comment by EricJizbaMSFT** [comment]
Our current plan is to use a shortened version of the template name (aka `HttpTrigger`) and add a `1` at the end to make it clear it's an instance of the template. This is a pretty common pattern, here are a few examples from simple templates in VS:

![Screen Shot 2020-02-25 at 4 08 27 PM](https://user-images.githubusercontent.com/11282622/75300228-10901d80-57ec-11ea-9dd1-a0553e19c0b3.png)![Screen Shot 2020-02-25 at 4 08 21 PM](https://user-images.githubusercontent.com/11282622/75300248-1f76d000-57ec-11ea-913c-142893dcbe8c.png)

![Screen Shot 2020-02-25 at 4 08 39 PM](https://user-images.githubusercontent.com/11282622/75300236-184fc200-57ec-11ea-9cc1-38ec84654fd5.png)![Screen Shot 2020-02-25 at 4 08 34 PM](https://user-images.githubusercontent.com/11282622/75300233-14bc3b00-57ec-11ea-9008-5282467661d4.png)

@kraigb @nigarfin thanks for your opinion. I think we're unlikely to change the above mentioned plan at this point just because this issue is so subjective and it was hard enough getting our own team to agree on that plan. If you still feel passionately about your suggestion - please find examples of that pattern used elsewhere (VS Code, VS, other IDEs/editors, etc.)

**Comment by kraigb** [comment]
Fair enough. In that case, however, if you follow the VS pattern, then you'd want to use HttpFunction1 rather than HttpTrigger1. That is, the function in code is not a trigger, it's a function. HttpFunction1 is distinct enough from other uses of "function" that it would still be easier to talk about in docs than "HttpTrigger1" even if not ideal.

At the same time, I think it'd make the most sense to use a pattern like HttpTriggerFunction1 and BlobTriggerFunction1, which makes the default names long enough (like WebApplication1) to be really clear that it's a *function* that handles a *trigger*. (Because BlobFunction1 doesn't make as much sense as HttpFunction1.) These longer names also imply "you should change the name to something more suitable," more so than, say, HttpTrigger1 or HttpFunction1.

I think such long names can work fine in the docs, because a name like "HttpTriggerFunction1" is unique enough that people wouldn't likely confuse it with anything else, and thus wouldn't need any qualifier. Uniqueness, in other words, is the real key to the name, and thus making it such a longer compound name actually works quite well.

Could that work?

**Comment by EricJizbaMSFT** [comment]
I just merged the logic to add `1` by default. @kraigb I'm not convinced on the long name - it looks a little gross to me. At this point I'm going to take the easy way out anyways - my team doesn't actually own the strings being discussed here. It's controlled by a template shared by VS Code, the portal, and VS. Here's where it comes from: https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/metadata.json#L2

You're welcome to continue the debate over in that repo
