### ISSUE TITLE
Consider to show short descriptions for Authorization level

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1788]
In this QuickPick:
![2020-01-14_15-17-38](https://user-images.githubusercontent.com/1898161/72351683-1bca3680-36e1-11ea-9106-17b56214d871.png)

consider to show a short description for the authorization levels and. Especially "Function" was a bit mysterious to me.

**Comment by weinand** [comment]
After navigating to the Azure portal I was able to learn that authorization level "Function" means "Function API key". So a more helpful wording and order would be this:
```
Anonymous (no API key)
Function API key
Admin API key
```

**Comment by EricJizbaMSFT** [comment]
Not sure I find the "API key" any more helpful. It's hard to boil this concept down to just a few words and put it in a quick pick so I guess I'd vote to keep it simple. In any case, this should be fixed in the templates themselves, which live here: https://github.com/Azure/azure-functions-templates
