### ISSUE TITLE
Bring Output window to front when deploying to Azure

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-azurefunctions#1790]
Since deploying to Azure takes some time (especially when a storage account needs to be created first), it would be helpful if the Output window is brought to the front so that more fine grained progress becomes visible.

**Comment by EricJizbaMSFT** [comment]
We provide a "view output" link once it gets to the "Deploying" stage, which has more interesting logs than the resource creation stage. We actually try to avoid opening the output window as much as possible (in favor of long-running notifications) because we had users complain that it was too intrusive. Related to https://github.com/microsoft/vscode-azureappservice/issues/455
