### ISSUE TITLE
Enable support for PowerShell 7 functions

### ISSUE THREAD

**Issue by eamonoreilly** [microsoft/vscode-azurefunctions#1866]
We need to create a setting FUNCTIONS_WORKER_RUNTIME_VERSION in the local.settings.json file with a value of ~7 to indicate to the functions host to run PowerShell 7 during function app creation.

**Comment by EricJizbaMSFT** [comment]
Can you give us more info on this? All the docs I see still say PowerShell 6. Also how does this translate when deploying to Azure? Can users target 6 or 7?

**Comment by eamonoreilly** [comment]
Hi Eric,
PowerShell 7 support is rolling out but won't be available until some time in March. The customer can choose the language version of PowerShell (6 or 7) during app creation in Azure although we will default to 7. 
When deploying to Azure, we should check the site config of the function app and look for a property under siteProperties called "PowerShellVersion". If this value exists, we need to make sure FUNCTIONS_WORKER_RUNTIME_VERSION in the local settings matches this version. If this property does not exist (older function apps), then we need to make sure FUNCTIONS_WORKER_RUNTIME_VERSION is set to 6 or else error out since the worker will be set to 6 in the cloud.

I don't think we will need for this work to be out until mid / late March. Please let me know if there is additional information I can provide.
Thanks,
Eamon

**Comment by sebastianzolg** [comment]
Is there any timeline for this?

**Comment by EricJizbaMSFT** [comment]
I investigated this a little while ago and unfortunately the sdk we're using (azure-arm-website) doesn't recognize the "PowerShellVersion" property on siteConfig and was filtering it out. We're finally unblocked on using the new sdk (@azure/arm-appservice - see https://github.com/microsoft/vscode-azuretools/issues/510), so I decided to wait until that's done (should be this milestone) instead of adding a temporary workaround

**Comment by EricJizbaMSFT** [comment]
New sdk doesn't seem to allow powerShellVersion either. Filed an issue here: https://github.com/Azure/azure-sdk-for-js/issues/10552
