### ISSUE TITLE
Possible typo 'debugger -> debuggee'

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurefunctions#191]
![functionstypo](https://user-images.githubusercontent.com/30420973/35419358-56133750-01ec-11e8-99ce-8a0198cf79b3.PNG)

**Comment by jdneo** [comment]
Hi @PrashanthCorp 

Thanks for the feedback, actually this is not a typo I think. 

Because when we debug the java function. we will start the function process first, then the java debugger will attach to the process. In this senario, the function process is debugged by the debugger, so we call it debuggee.

BTW, I'm more interested in the reason why you met this problem. I guess you met this issue because the function process could not be started correctly. Could you please provide more details on that?

**Comment by EricJizbaMSFT** [comment]
Closing this for a variety of reasons:
1. Inactivity
1. The message is debatably confusing, but not a typo
1. The message isn't coming from this repo
