### ISSUE TITLE
After deployment, @azure/functions is no longer defined.

### ISSUE THREAD

**Issue by ShawnTalbert** [microsoft/vscode-azurefunctions#1930]
Maybe I'm doing something wrong, but it appears the `Azure Functions: Deploy to Function App...` process does an `npm install` then does `npm prune --production` which removes the @azure/functions package installed originally.

So, after deploy my function code won't compile. :\

I started the project using `Azure Functions: Create New Project...`, typescript, and `HttpTrigger` as my first function.

This generates a `package.json` with dependencies like so:
```json
{
  "name": "FunctionApp2",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "prestart": "npm run build",
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {},
  "devDependencies": {
    "@azure/functions": "^1.0.2-beta2",
    "typescript": "^3.3.3"
  }
}
```

and an azure function that starts like this:

```typescript
import { AzureFunction, Context, HttpRequest } from "@azure/functions"

...

```
Is this expected behavior? the `npm prune` removes everything.

Am I supposed to rerun `npm install` manually after each deploy?

I'm on Azure Function 0.20.2

**Comment by EricJizbaMSFT** [comment]
@ShawnTalbert yes that is the default behavior. We remove devDependencies so that deploying is faster and since those are not needed in production. It doesn't really make a difference for a simple app like this, but it will matter the larger the project gets.

That being said, this is all configurable based on your personal tastes. For example, this is controlled by the setting `azureFunctions.preDeployTask` in the file `.vscode/settings.json`. You can remove that setting if you don't want to run prune.

**Comment by ShawnTalbert** [comment]
Thanks Eric. So it's expected that post deployment my code no longer compiles? That seems like a sad user experience - deployment leaves me with a broken build. It's also sad to think I need to run an `npm install` after each deployment.

Is there a way to tell the system to _not deploy_ dev dependencies without wiping them out?
Or perhaps a way to control/bundle only the files we need, and deploy only those? It kinda looks like the deployment task just zips up the entire folder and sends it to Azure storage?

**Comment by EricJizbaMSFT** [comment]
Well it'll automatically run `npm install` if you debug, but that wouldn't really work if you have a watch task going... How do you normally compile your code?

We use a `.funcignore` file to exclude things when deploying. It would be hard to use this for dev dependencies though because one dependency could have a bunch of child dependencies.

I see the pain here and we're open to suggestions. We've discussed one option here: https://github.com/microsoft/vscode-azurefunctions/issues/1528. Another idea is to add a `postDeployTask` setting (analogous to `preDeployTask`) which would run `npm install`

**Comment by ShawnTalbert** [comment]
I typically have a `tsc --watch` running for that near-instantaneous transpiling goodness.
Also, the editor immediately (rightfully) shows me the red-squiggles in the `import` statement immediately following the _deploy_.

Thanks for the #1528 reference. I didn't see it when I went looking. I can take up the discussion there?

Perhaps doing `npm prune --production` then `npm install` wouldn't be bad for a single function with simple dependencies. I'd argue any single Azure function should probably stay pretty lean. However, if we must deploy ALL functions in a project in one go, that npm _reinstall_ could be a pain.  I'd like (_expect?_) to be able to deploy _individual_ functions rather then the entire Function App. Is that possible with the existing tooling? It is possible my functions are logically orthogonal - I just want them to share resources, and hence should be deployed independently of one another?

**Comment by EricJizbaMSFT** [comment]
Yeah let's continue in #1528. I don't think it's possible to deploy a single function. I don't think that's our limitation in VS Code - I think that's a limit of the platform in Azure
