### ISSUE TITLE
"Failed to detect running Functions host within "60" seconds" after cancelling build and attempting rebuild

### ISSUE THREAD

**Issue by meds** [Microsoft/vscode-azurefunctions#194]
I run azure functions locally (.net core 2.0), after doing a build and running it (F5) I terminate the app by going into terminal and hitting ctrl-c

When I try to run the functions again I get an error after a while saying 'error failed to detect running functions host within "60" seconds', if I hit close and F5 again the functions run fine.

Ideally I would like the functions to hot compile without needing to be  terminated and run again but failing that would be nice to get consistent  rebuilds.

**Comment by EricJizbaMSFT** [comment]
@meds we're working on this issue - thanks. Is it blocking you? If so, here are a few potential workarounds:
1. Remove `"preLaunchTask": "build"` in you 'launch.json' file. Since you have to restart the functions host every time and the 'runFunctionsHost' task already depends on the 'build' task, re-building is unnecessary and might cause part of the 60 second delay
1. Use `"processId": "${command:pickProcess}"` instead of `"processId": "${command:azureFunctions.pickProcess}",` in your 'launch.json' file. This will let you manually select the functions process instead of us trying to automatically detect it within 60 seconds. Of course, this means you will have to have the func host running before you F5
