### ISSUE TITLE
Azure Function v3 will not debug

### ISSUE THREAD

**Issue by mattc-eostar** [microsoft/vscode-azurefunctions#1952]
Repro steps:
1. Create new C# Azure function (v3)
2. Use default HTTPTrigger template
3. Debug > Start Debugging

`dotnet --version` --> 3.1.102
`func --version` --> 3.0.2245
OS -> macos

Terminal output:
```
> Executing task: dotnet clean /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1
```

If I run `dotnet clean /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary` manually, it completes successfully. If it runs through debug, it fails.

I tried removing `"terminal.integrated.shell.osx": "/bin/bash"` from settings.json, but that didn't seem to have any effect.
____________
Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "clean" failed with exit code "1".

Version: 0.20.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:353:86654
l.fire extensionHostProcess.js:48:541
y.$onDidEndTaskProcess extensionHostProcess.js:746:693
```

</details>

**Comment by EricJizbaMSFT** [comment]
@mattc-eostar what directory is the default when you open a terminal in VS Code? Hopefully it should be the workspace you're in. We've had people with issues in the past where they have a profile that changes the default working directory https://github.com/microsoft/vscode-azurefunctions/issues/1260#issuecomment-489612400

**Comment by mattc-eostar** [comment]
@EricJizbaMSFT the working directory is correct within the terminal

**Comment by EricJizbaMSFT** [comment]
Sorry I don't really know what could be going on here. At the end of the day, we're writing the default tasks when you create a project, but after that it's just using VS Code's standard task system. It could be related to your project, your terminal config, I'm not sure.

If you're still having issues, can you post a screenshot of your workspace? Also could you try creating a simple console app with `dotnet new` and see if a similar problem reproduces unrelated to Azure Functions? The C# extension should prompt to add some default tasks. This would help us narrow down where the issue is
