### ISSUE TITLE
Function App Upload Failed - MD5 hash mismatch between local and uploaded

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-azurefunctions#1983]
Does this occur consistently?  Yes
Repro steps:

1. Deploy function from r-click context menu 'Deploy to function app'
2. .python_packages created, zip file created successfully
3. Upload fails (see error message).

I have deployed my funciton app to azure many times, but just randomly started getting this error.

I have since tried:
* Delete and recreate all azure resources (function app, app service plan, storage)
* Updated azure-functions-core-tools@3
* Reinstalled vscode azure functions extension
* Reinitialized the project with azure functions

 but the issue persists. The deployment succeeds if I use `"azureFunctions.scmDoBuildDuringDeployment": true,` to build the project remotely, but that takes a lot longer and I would really like to be able to build locally as usual.

I see that @EricJizbaMSFT was working on [658](https://github.com/microsoft/vscode-azuretools/pull/658) recently, which seems like it could be related?

Action: azureFunctions.deploy
Error type: Error
Error Message: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

Version: 0.21.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:468:18460
fulfilled extension.bundle.js:468:16860
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jaymegordo do you get the same error if you deploy directly from the func cli?

**Comment by jaymegordo** [comment]
@EricJizbaMSFT No errors when using the cli, I can deploy successfully with:

`func azure functionapp publish myappname --build-native-deps` (for anyone else reading)

Also, I tried to deploy a second project's function app with the context menu and it also failed with the exact same MD5 hash error.

**Comment by joeyslack** [comment]
This issue is happening for me, on latest VSCode and Azure Functions extension. It's a nodejs app. I receive the error, after clicking "Deploy to Function App": "Error: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy."

Looking at the log files, prior to that error, I'm getting an error as the script is trying to access a file that no longer exists. I can presume that this md5 mismatch error is looking for a file that I've since deleted - the better question is why are you looking for files that I don't have? This file is not referenced from any new source, however, you're clearly storing reference to this file in the cloud function, and it's looking for a folder/file that doesn't exist. Why can't you let me delete my old deployment entirely? I don't like the idea of having to do md5 check against a previously failed deployment, can't you just delete my old deployments entirely, forgoing the need to do md5 comparison that will always fail?

**Comment by joeyslack** [comment]
Had the same issue, with a `nodejs` app: 

> Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

via the Azure Functions Extension upload button.

To resolve, I used @jaymegordo solution above. It works, when building locally, but when I want to build on azure (--build remote), as suggested by the command line helper, the build fails, as the `tsc` lib cannot be found: 

> Error: Cannot find module '../lib/tsc.js'

**Comment by EricJizbaMSFT** [comment]
@joeyslack I'm not quite sure how the moment stack overflow bug is related to the error. We only use that for the name of the blob, but I don't think the name affects the md5 hash. Can you expand on how that might fix it?

I can't reproduce this on my local machine with a simple python project. Does it reproduce for you with just an http trigger? Could either of you by chance share your project on GitHub so that I could try? That might help me debug the tsc issue you mentioned as well

**Comment by EricJizbaMSFT** [comment]
If you want a different workaround, I've added a setting to disable this validation:

> "azureFunctions.suppressMd5Validation": true

It won't be released for a bit, but you can install [this insiders build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17165&view=results) with [these instructions](https://aka.ms/azcodeinsiders) to get it early.

**Comment by joeyslack** [comment]
@EricJizbaMSFT Thanks, that seems to have worked for now. Appreciate your help.

**Comment by yareyaredesuyo** [comment]
I got this error when using linux container and looks like very crucial bug (It means, cannot update files by default). 

So this option should be set to default settings. 

```
"azureFunctions.suppressMd5Validation": true
```

**Comment by EricJizbaMSFT** [comment]
@yareyaredesuyo I'm still looking for sample projects to help me reproduce this on my machine. If yours exists on GitHub and you can point me to it that would be very helpful.

We don't want to turn off md5 validation by default - ideally we figure out why people are getting this error consistently. We expect _some_ md5 validation errors, but they should be rare and transient
