### ISSUE TITLE
Debugger not working, breakpoints not being triggered

### ISSUE THREAD

**Issue by y0m0** [microsoft/vscode-azurefunctions#1995]
Does this occur consistently?
Yes

Repro steps:
1. Create new project by using "Azure Functions: Create new project..." 
3. select "HTTP trigger" function
3. select language C#
4. Wait for project to be created
5. Set some breakpoints
6. Run azure function with debug (F5)

extra info: 
vscode settings.json
```
{
  "azureFunctions.deploySubpath": "bin/Release/netcoreapp3.1/publish",
  "azureFunctions.projectLanguage": "C#",
  "azureFunctions.projectRuntime": "~3",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "publish"
}
```

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.21.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:526:95817extension.bundle.js:526:95817
fulfilled extension.bundle.js:526:94354
```

</details>

**Comment by EricJizbaMSFT** [comment]
@y0m0 I see reports of this error occasionally, but it never reproduces on my machine. If you can give me more info to find the root cause that would be very helpful. As a starting point:
1. What version of `dotnet` do you have installed?
1. What verison of the `func` cli?
1. I assume the build task succeeded?
1. Can you copy all logs of the "func host start" task (It should pop up automatically when you F5)
