### ISSUE TITLE
Better support for exsting Functions apps

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#203]
There is some degradation in the experience for users that have existing Functions Apps when it comes to locally debugging the app. Here are a few ideas for improving that.

Note that `$ func init` creates a launch.json that doesn't include starting up the functions host. I can work with them to get the tasks.json added that matches ours, that may help a bit.

### Contribute Functions launch config to the debugger

There is a way to contribute generic launch configs to the debugger that show up if a user hits F5 and VS Code doesn't know how to launch. 

![image](https://user-images.githubusercontent.com/1186948/35749989-460c8bbe-0808-11e8-9265-4ef939c7d456.png)

### Allow user to setup launch config

I know you can reinitialize the app to write out the launch config, but it's not super discoverable for users. Maybe add a button to "setup Functions debugging" that will add/overwrite the launch config and tasks.
 
### Better handling of language and runtime selection

The prompts for understanding the workspace ask for the runtime twice. Repro:

```sh
$ func init
$ code .
```

Now add a new function to the app, you'll be promoted to select the runtime version, set the runtime. Next you get prompted for the language, then again for the runtime version.

It seems like the first check could be skipped completely.

**Comment by ahmelsayed** [comment]
let me know what the `func` cli can do to help here. I just got sometime to use the vscode extension and it's doing an awesome job so far 👍. I'd love to have a better experience for users starting from the cli.

**Comment by EricJizbaMSFT** [comment]
@ahmelsayed there's two things for sure the cli can do:

1. Add this extension as a recommended extension for the workspace. This is done by adding an 'extensions.json' file in the '.vscode' folder with the following content:
```
{
    "recommendations": [
        "ms-azuretools.vscode-azurefunctions"
    ]
}
```
1. Remove '.vscode' from the default gitignore. We definitely want users to check in code in their '.vscode' folder since it contains debug configurations, etc.

I planned on submitting a PR to the cli repo eventually, but feel free to take care of it yourself if its easy for you.

**Comment by EricJizbaMSFT** [comment]
Opened a separate issue to track the work in the functions cli: https://github.com/Azure/azure-functions-core-tools/issues/394
