### ISSUE TITLE
Error: Encountered an error (ServiceUnavailable) from host runtime when i am trying to deploy to a linux server

### ISSUE THREAD

**Issue by xtianus79** [microsoft/vscode-azurefunctions#2045]
I have seen this issue repeatedly closed down and would like to ask why? Also, Why is this happening?

```
1:54:26 PM ai-xxxxxx-token-fa: WARNING: Using zip deploy because scm type "VSTSRM" is not supported on Linux consumption
1:54:27 PM ai-xxxxx-token-fa: Creating zip package...
1:54:27 PM ai-xxxxx-token-fa: Starting deployment...
1:54:28 PM ai-xxxxx-token-fa: Uploading zip package to storage container...
1:54:31 PM ai-xxxxx-token-fa: Deployment successful.
1:54:31 PM ai-xxxxx-token-fa: Started postDeployTask "npm install".
1:54:42 PM ai-xxxx-token-fa: Syncing triggers...
1:54:47 PM ai-xxxx-token-fa: Syncing triggers (Attempt 2/6)...
1:54:58 PM ai-xxxx-token-fa: Syncing triggers (Attempt 3/6)...
1:55:19 PM ai-xxxx-token-fa: Syncing triggers (Attempt 4/6)...
1:55:59 PM ai-xxxxx-token-fa: Syncing triggers (Attempt 5/6)...
1:57:20 PM ai-xxxxx-token-fa: Syncing triggers (Attempt 6/6)...
1:57:21 PM: Error: Encountered an error (ServiceUnavailable) from host runtime.

```

**Comment by EricJizbaMSFT** [comment]
There's a whole bunch of reasons this could be happening and unfortunately we (the VS Code extension) don't have access to the full logs to understand why it's happening. I would start with [these troubleshooting tips](https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503) or contact Azure support (there should be a help button in the portal) since they should have access to more logs.

If you want us to investigate on the VS Code side - we would need much more detailed repro steps including how you created your local project, how you created the function app in Azure, etc.

**Comment by xtianus79** [comment]
i moved over to a new app which resolved that issue. seemed to be in a bad state.
