### ISSUE TITLE
Miss "(Read only)" next to "Functions/Proxies" nodes for Python Function App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2059]
**OS**: win10
**Build Version**: [20200417.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17972&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a new Python Function App.
2. Deploy a Python project to it.
3. Expand the Function App and check the nodes.

**Expect:**
Display "(Read only)" next to "Functions/Proxies" nodes.

**Actual:**
Miss "(Read only)" next to "Functions/Proxies" nodes.
![image](https://user-images.githubusercontent.com/57662131/80442961-a8bb9780-8940-11ea-9c70-c2665f536a7f.png)

**More Info:**
1. This issue only reproduces on Python Function App.
2. Application Settings doesn't contain the app setting ` WEBSITE_RUN_FROM_PACKAGE`.

**Comment by EricJizbaMSFT** [comment]
The label is accurate in this case. Since it doesn't have `WEBSITE_RUN_FROM_PACKAGE`, it is editable. We have a few other issues discussing whether or not it should actually have that setting. For example https://github.com/microsoft/vscode-azurefunctions/issues/1847 and https://github.com/microsoft/vscode-azurefunctions/issues/1465
