### ISSUE TITLE
Stop Debugging doesn't cause the host task to stop

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2091]
**OS:** Win10
**Build Version:** [20200513.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19233&view=results)

**Repro Steps:**
1. Open a function project in VS Code.
2. Debug it, then stop debugging immediately.

**Expect:**
The host task is stopped.

**Actual:**
Stop Debugging doesn't cause the host task to stop.

**Comment by EricJizbaMSFT** [comment]
I see how this is annoying, but going to close as "wont-fix" for a variety of reasons:
1. There's risk involved if we add custom logic to stop tasks. VS Code or the func cli or something doesn't handle it well and we run into problems like #1401
1. There's an easy workaround - users can click the trash can icon to stop the task
1. We're consistent with standard VS Code behavior here. For example, if I do "[Launch Extension (webpack)](https://github.com/microsoft/vscode-azurefunctions/blob/master/.vscode/launch.json#L23)" from our repo, the webpack task (which takes an annoyingly long time) keeps going even if I stop debugging. I have to stop it manually. In that sense this issue could even be "upstream" instead of "wont fix"
