### ISSUE TITLE
Project created several folders down is not automatically detected

### ISSUE THREAD

**Issue by SeaDude** [microsoft/vscode-azurefunctions#2134]
After creating a new Python project using the extension, the project is not listed under "Functions/MySubscription". The files were all created, but the project is not listed.

I'm using the latest VS Code for Linux. Please advise. Thank you

**Example**:
![noProject](https://user-images.githubusercontent.com/8636973/83155107-c140de00-a0b5-11ea-93bd-ecae94992858.gif)

**Comment by EricJizbaMSFT** [comment]
Looks like a bug when you create a project several levels below your opened workspace. I'll look into fixing that, but in the meantime you have a few ways you can workaround it:

1. Open the exact folder you want to use in VS Code _before_ you create the project
1. If you want to keep your current folder open instead of the exact project folder, you can specify "azureFunctions.projectSubpath" in your VS Code settings (`.vscode/settings.json`). It would look something like this:

Settings:
<img width="461" alt="Screen Shot 2020-05-28 at 10 14 57 AM" src="https://user-images.githubusercontent.com/11282622/83172266-30c1c800-a0cc-11ea-8c9d-4f5686224c33.png">

Folder view:
<img width="223" alt="Screen Shot 2020-05-28 at 10 15 16 AM" src="https://user-images.githubusercontent.com/11282622/83172268-328b8b80-a0cc-11ea-8100-b7b6435000af.png">

Azure view:
<img width="223" alt="Screen Shot 2020-05-28 at 10 15 06 AM" src="https://user-images.githubusercontent.com/11282622/83172267-31f2f500-a0cc-11ea-9540-584928b9af90.png">

This will add a "Local Project" view in the Azure Functions tree. For it to show up under your subscription, you would need to deploy using the blue up arrow.

**Comment by SeaDude** [comment]
#1 above worked fine. Thank you for acknowledging the bug (so I know I'm not insane!) and providing unblockers for me to continue dev. 
I appreciate that.

**Comment by EricJizbaMSFT** [comment]
Glad that worked! Re-opening the bug for our own tracking purposes
