### ISSUE TITLE
 Encountered an error (ServiceUnavailable) while deploying function

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [microsoft/vscode-azurefunctions#2148]
Does this occur consistently? Yes.

Repro steps:

1. Create Azure function using App Service Plan
2. Publish function from VScode.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.22.1
OS: linux
OS Release: 5.3.0-53-generic
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2840812
retryCallback extension.bundle.js:225:114550
retryCallback extension.bundle.js:157:31063
extension.bundle.js:157:32676
handleRedirect extension.bundle.js:171:7752
extension.bundle.js:157:29848
Request._callback extension.bundle.js:1:670871
Request.n._callback.n.callback.n.callback extension.bundle.js:201:4483
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17592
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16382
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
There's a whole bunch of reasons this could be happening and unfortunately we (the VS Code extension) don't have access to the full logs to understand why it's happening. I would start with these troubleshooting tips or contact Azure support (there should be a help button in the portal) since they should have access to more logs.

If you want us to investigate on the VS Code side - we would need much more detailed repro steps including how you created your local project, how you created the function app in Azure, etc.

Other users have had success with trying to deploy to a new app.

**Comment by nights99** [comment]
I may have hit this same problem deploying a new version of a timer triggered function; I've raised this on the Azure Q&A: https://docs.microsoft.com/en-us/answers/questions/38253/azure-ttime-triggered-function-fails-to-deploy-wit.html I'd be interested to know if the original posters issue also used a timer trigger, and if the same "Syncing triggers" retry output was seen

**Comment by EricJizbaMSFT** [comment]
@nights99 the link you pasted doesn't seem to be working for me. There's a lot of different reasons people could get a "ServiceUnavailable" error, so probably best for you to create a new issue with your own detailed repro steps
