### ISSUE TITLE
Unable to start the project locally

### ISSUE THREAD

**Issue by hardEight** [microsoft/vscode-azurefunctions#2149]
Does this occur consistently? Yes
Repro steps:
I try to attach to the .NET Functions and it crashes. I've uninstalled and re-installed VSCode, the Azure function extensions etc. The Bundle config that the error says to remove, it automatically regenerated when trying to start the project.

1.Press Start Debugging
2. This error is generated:
Extension bundle configuration should not be present for the function app with pre-compiled functions. Please remove extension bundle configuration from host.json: C:\AzureFunction\bin\Debug\netcoreapp3.1\host.json

Here is the output from the Terminal
Executing task: C:\Program Files\dotnet\dotnet.exe build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  AzureFunction -> C:\AzureFunction\bin\Debug\netcoreapp3.1\bin\AzureFunction.dll

Terminal will be reused by tasks, press any key to close it.

> Executing task: func host start <

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.2508 Commit hash: 4da36643c32783a832094318afcd679fa9d76455)
Function Runtime Version: 2.0.13351.0
Extension bundle configuration should not be present for the function app with pre-compiled functions. Please remove extension bundle configuration from host.json: C:\AzureFunction\bin\Debug\netcoreapp3.1\host.json
The terminal process terminated with exit code: 1

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Functions host is no longer running.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:334:101651extension.bundle.js:334:101651
fulfilled extension.bundle.js:334:99073
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hardEight how did you create this local project? Also - what do the settings look like in `.vscode/settings.json`? 

> it automatically regenerated when trying to start the project.

This shouldn't be happening for C# projects. That's why I'm curious about your settings

**Comment by hardEight** [comment]
Hi Eric,
I followed the directions for developing locally in the Azure Portal. I was
able to create C# function apps previously, this one I was hoping to create
a Powershell App. I assume that may be part of the issue?

Here are the settings you requested.
{
  "azureFunctions.deploySubpath": "bin/Release/netcoreapp3.1/publish",
  "azureFunctions.projectLanguage": "C#",
  "azureFunctions.projectRuntime": "~3",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.preDeployTask": "publish"
}

**Comment by matthijsvdr** [comment]
So I and a college (and someone on stackoverflow) face a similar problem but with python (different laptops, same project, different branch, different python version (3.8.0, 3.8.1) it died on the same day)

Monday evening -> everything worked fine, was able to run/debug and deploy.
Tuesday morning -> Running the function using vscode no longer works, running the function using `func host start` on the commandline works fine but i'm unable to attach a debugger to it.
(The laptop did crash during the night and was rebooted) 

When running it crashes on imports of grpcio inside the azure functions. If these are fixed by installing the packages, it will crash on a protobbuf import.

**Comment by EricJizbaMSFT** [comment]
@hardEight yeah if you were trying to create a PowerShell app, it's weird to me that the projectLanguage is set to "C#". You selected "PowerShell" when creating the project? Double check your _user_ settings (as opposed to _workspace_ settings - see more [here](https://code.visualstudio.com/docs/getstarted/settings)) to make sure "projectLanguage" isn't set. If it's set in the _user_ settings, we use that language when creating new projects instead of prompting each time.

@matthijsvdr your issue sounds a bit different. Please file a new issue with the full errors you mentioned

**Comment by hardEight** [comment]
Thanks Eric, after uninstalling and reinstalling .NET 2.something and VS
code and Azure Functions a few times, I seem to have stumbled upon a
working set! Thanks.
