### ISSUE TITLE
[Discussion] Handle deps and funcpack?

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#218]
I have a bot app that I'm deploying and it requires some external deps. Right now, I have the app setup so that the function includes a package.json which is packed up into a `.funcpack` directory and deployed.

There are a few issues with the setup today. My deployment process is

```sh
$ cd messages && npm i
$ cd -
$ funcpack pack .
$ rm -rf messages/node_modules # keeps the deployment small
```

Then deploy the workspace using the extension. 

I have to run through the "build" process because the extension only supports webdeploy; the platform provides an envar for `SCM_RUN_FUNCPACK` which is only honored for git deployments.

I see a couple of things that need to happen to make this work and I'd like to know what others think.

- [ ] Work with Functions team to enable funcpack to run on webdeploy
- [ ] Run `$ funcpack pack .` as part of debugging (need to figure out how to determine this)

**Comment by fiveisprime** [comment]
I think a good starting point is if there is a `.funcpack` directory, prompt to deploy only the contents of that directory.

**Comment by burkeholland** [comment]
I think there are 2 main things that we can do to improve the local development workflow...

1. Generate a package.json file for people
2. Make funcpack work locally

On number 2, to be more specific, when you `funcpack` from the command line, you lose the ability to debug your function locally because now the minified file is being loaded. Ideally, the minified file would point back to the original so that you can funcpack, and still set breakpoints in your code normally. This is similar to the way create-react-app works today.
