### ISSUE TITLE
Not showing templates from bundle version 1.3.0

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#2193]
The current version of bundles is 1.3.0 and should contain Durable Functions templates for Python. However, they're not showing for me. Do I need to clear a cache before they appear?

![image](https://user-images.githubusercontent.com/3982077/85983909-2c275280-b99d-11ea-812e-8163601ef44f.png)

In the same project, `func new` shows the templates:

![image](https://user-images.githubusercontent.com/3982077/85983973-46613080-b99d-11ea-8d45-7a31eb28732a.png)

**Comment by EricJizbaMSFT** [comment]
@anthonychu did you ever use `FUNCTIONS_EXTENSIONBUNDLE_SOURCE_URI` to test the staging templates in this instance of VS Code? If so, that might be messing with our caching logic. The staging feed was on 1.3.0 for several months and I'm pretty sure multiple changes were pushed to the same version. It's possible we cached the 1.3.0 templates the very first time you tested with that env var (before durable templates were added?) and we've never updated the cache since then because you're technically still on the same version.

As a workaround, you can temporarily switch to the staging template source (which is currently at 1.3.2) and then switch back to normal. This should delete the "old" 1.3.0 templates and get you back on track
1. Load VS Code with `FUNCTIONS_EXTENSIONBUNDLE_SOURCE_URI` set to `https://functionscdnstaging.azureedge.net/public`
1. Start the "Create Function..." flow just to make sure it updates the templates
1. Reload VS Code without the environment variable

I can investigate a fix on our side, but I don't think this will be a problem very often. External users probably won't be testing the staging template source, and hopefully the staging source won't be stuck on the same version for months like it was.

**Comment by anthonychu** [comment]
That worked! I don't think I ever set that variable on my local machine, but for a while I was running a custom build of the extension that was modified to bypass the cache and use the staging feed to test the Python Durable templates. That might have messed things up. 😬

Thanks for adding support for `FUNCTIONS_EXTENSIONBUNDLE_SOURCE_URI` BTW. Super useful. 👍

**Comment by MaximRouiller** [comment]
I'm also seeing that issue. 
![image](https://user-images.githubusercontent.com/209384/87084521-6219d180-c1fc-11ea-9a97-520c529570ab.png)

**Comment by MaximRouiller** [comment]
Never used that variable and I can reproduce. Can we reopen?

https://github.com/Azure/azure-functions-durable-python/issues/153

**Comment by MaximRouiller** [comment]
To be clear, it shows up in `func new`. Just not in vscode.

**Comment by EricJizbaMSFT** [comment]
@MaximRouiller Anthony's situation was almost certainly unique to his machine's setup related to the staging feed. If you would like us to investigate your issue, please open a new issue with your own detailed repro steps
