### ISSUE TITLE
Unable to deploy Azure Function from VSCode - remote runtime does not match local runtime

### ISSUE THREAD

**Issue by AlxndrMlk** [microsoft/vscode-azurefunctions#2219]
Does this occur consistently? Yes 
Repro steps:

1. I downloaded remote settings from Azure, this sets `"FUNCTIONS_WORKER_RUNTIME": "python3.8"` in `local.settings.json`
2. The runtime that I use in VSCode is `Python 3.8`
3. Despite this I receive the following error message every time I try to deploy the function:
`The remote runtime "python3.8" for function app "fa-cdlmdmml-dev01" does not match your local runtime "python".`

Action: azureFunctions.deploy
Error type: Error
Error Message: The remote runtime "python3.8" for function app "fa-cdlmdmml-dev01" does not match your local runtime "python".

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:164:361564extension.bundle.js:164:361564
extension.bundle.js:164:361116extension.bundle.js:164:361116
s extension.bundle.js:164:360802
verifyVersionAndLanguage extension.bundle.js:164:361280
Object.<anonymous> extension.bundle.js:164:362285
fulfilled extension.bundle.js:164:360870
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@AlxndMlk how exactly did "FUNCTIONS_WORKER_RUNTIME" get set to "python3.8"? I think it has to be just "python"

**Comment by AlxndrMlk** [comment]
@EricJizbaMSFT: I currently don't have the full information on this as another team was responsible for the service setup. From your question, I understand that "python3.8" should not be a default value for `"FUNCTIONS_WORKER_RUNTIME"`. Is that correct?
I tried to change `"FUNCTIONS_WORKER_RUNTIME"` to just `"python"` in the portal, but this resulted in `Application Error`.

**Comment by EricJizbaMSFT** [comment]
That is correct - "FUNCTIONS_WORKER_RUNTIME" is only used to select the runtime, not the version. Here are [the docs](https://docs.microsoft.com/azure/azure-functions/functions-app-settings#functions_worker_runtime). There's a separate property ("linuxFxVersion") that controls the version of Python. However, it's not an application setting and I don't think it can be changed after the resource is created.

In terms of "Application Error", maybe restarting the function app would help? Otherwise, I would talk to whoever setup the service as it might just be broken from the start. When I try to run locally with it set to "python3.8" I get several different errors:

> Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]

> [7/8/2020 5:30:29 PM] A host error has occurred during startup operation '79201397-b799-456a-aa06-f2595d9b2b32'.
> [7/8/2020 5:30:29 PM] Microsoft.Azure.WebJobs.Script: Did not find functions with language [python3.8].

> Value cannot be null. (Parameter 'provider')

**Comment by AlxndrMlk** [comment]
Thank you @EricJizbaMSFT. I addressed this with the deployment team and you're right. There are some issues on their side. 

Thank you for your support.
