### ISSUE TITLE
error when deploying python azure python function which has pyodbc library 

### ISSUE THREAD

**Issue by rodrigopessoa1979** [microsoft/vscode-azurefunctions#2425]
I have an Azure function witch python that connect a database azure SQL, I’m using the package pyodbc to connect database. 
On my computer it's working, but when I deploy via vscode, azure does all the python installations based on the requirements and he tries to do the download through website https://github.com/pypa/pip/issues/8368./n , which is out

Last week it was working and now don't work

**Comment by EricJizbaMSFT** [comment]
Not sure we can do much about the issue you mentioned, but as a workaround you can switch from remote build to local build with these docs: https://github.com/microsoft/vscode-azurefunctions/wiki/Remote-Build

Local build means it'll deploy and use whatever is on your local machine instead of trying to do the python installations in Azure.
