### ISSUE TITLE
Deploy to Function App not working.

### ISSUE THREAD

**Issue by c-lamont** [microsoft/vscode-azurefunctions#2480]
Does this occur consistently? Yes
Repro steps:
1. Right click function and and select "Deploy to Function App..."
2. Select the desired subscription
3. Select the desired Function App
4. Nothing happens for a couple minutes, then "Report error" button appears.

Action: azureFunctions.deploy
Error type: InternalServerError
Error Message: Encountered internal server error. Diagnostic information: timestamp '20201019T195701Z', subscription id 'bf62bbfa-cdd0-4e13-b1e6-a509441e7b6e', tracking id '322cee03-3614-4b4f-a973-f150f67124eb', request correlation id '322cee03-3614-4b4f-a973-f150f67124eb'.

Version: 0.24.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Unfortunately these types of errors are often from Azure and it could be caused by a variety of things. We'll need some more info to help diagnose, for example:

1. What region?
1. What plan type (consumption/premium/etc.)
1. Is this a brand new project?
1. What type of triggers do the project have?
1. Do you have full access to the subscription?

It might help to just try creating a new function app as well.

**Comment by c-lamont** [comment]
@nturinski Thanks for the response.

It seemed Azure was down during this error as even the portal was not loading. I left it for a night and it was back working again.
