### ISSUE TITLE
sadasd

### ISSUE THREAD

**Issue by mturde** [microsoft/vscode-azurefunctions#2512]
Does this occur consistently? <!Yes>
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription '7b93798f-c5a4-4c35-a57a-dba0aeb07e60' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 1.0.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
extension.bundle.js:48:167633extension.bundle.js:48:167633
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
It looks like your account has been disabled. If you would like to re-enable it, you can follow the instructions [here](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/subscription-disabled)

If you have done this and it's still not working, then it's most likely due to this external issue https://github.com/microsoft/vscode-azure-account/issues/137
