### ISSUE TITLE
Create Function not listing C# templates

### ISSUE THREAD

**Issue by Blackbaud-PeteLukich** [microsoft/vscode-azurefunctions#2588]
Perhaps similar to [this past issue](https://github.com/microsoft/vscode-azurefunctions/issues/234)?

I'm following [this tutorial ](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-create-first-csharp?pivots=code-editor-vscode#add-functions-to-the-app)to create a Durable Function.  The first step to create the empty project works fine. The second step says to press F1, choose "Azure Functions: Create Function...", then choose the template for "Durable Orchestration".  The only templates that I see listed are: "RabbitMQTrigger" and "Http trigger(s) from OpenAPI V2/V3".

Is this is an issue with my local machine? Or is the VSCode Extension querying a remote list of templates that is broken?

There is also a "Change template filter" option in the "Select a template for your function" menu. When I change this filter to "All", I still only see these two templates.

**Comment by BorCob** [comment]
I encountered this exact same issue and wasted a few hours finding that this is obviously a bug that magically appeared. The only items showing up are indeed 'RabbitMQTrigger' and 'Http trigger(s) from OpenAPI V2/V3', which are both unrelated to this template overview.

I tried 'func templates list' in the Terminal, which gives me this for C#:

> C# Templates:
>   Azure Blob Storage trigger
>   Azure Cosmos DB trigger
>   Durable Functions activity
>   Durable Functions HTTP starter
>   Durable Functions orchestrator
>   Azure Event Grid trigger
>   Azure Event Hub trigger
>   HTTP trigger
>   IoT Hub (Event Hub)
>   Azure Queue Storage trigger
>   SendGrid
>   Azure Service Bus Queue trigger
>   Azure Service Bus Topic trigger
>   SignalR negotiate HTTP trigger
>   Timer trigger

Looks perfectly OK. So how does the extension screw up?

**Comment by ejizba** [comment]
This was a temporary issue with the remote list of templates, which has since been fixed. However, if you are one of the unlucky few who loaded templates during that time, you will need to clear your cache or wait for us to release an update in the next few days which will automatically fix this for you.

To clear your cache, **delete these folders** and then **reload VS Code**:
Mac:
`$HOME/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/` and
`~/.templateengine/AzureFunctions-VSCodeExtension`

Windows:
`%AppData%\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates` and
`%USERPROFILE%/.templateengine/AzureFunctions-VSCodeExtension`

**Comment by BorCob** [comment]
Thanks for your reply @ejizba. Initially I just removed the files in those directories, but you need to remove the directories themselves as well. It now works.

**Comment by ejizba** [comment]
Glad you got it working and thanks for the tip!

**Comment by ejizba** [comment]
Just released v1.1.0 of the extension, meaning this should be working even if people don't clear the cache
