### ISSUE TITLE
Azure Function extension will kill my function process which is started by my shell type task

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/vscode-azurefunctions#2619]
Hi, I have a project which has a sub-folder *api/* which contains a httpTrigger function app. I wrote a task in `.vscode/tasks.json` to start the function app using **shell** type task instead of **func** type.
```json
{
    "type": "shell",
    "command": "func host start",
    "label": "Start function app",
    "isBackground": true,
    "options": {
        "cwd": "${workspaceFolder}/api"
    }
}
```

After successfully run this task and start my function app, I launch my frontend code in a `pwa-msedge` web client.
```
{
    "name": "Local Debug Tab App(Teams Web Client)",
    "type": "pwa-msedge",
    "request": "launch",
    "url": "https://teams.microsoft.com/_#/l/app/6f75262e-d59d-4b2d-8edd-60bc32ca2118?installAppPackage=true",
    "webRoot": "${workspaceFolder}"
}
```

The function process is listening at `http://localhost:7071` and will be called by the web client. However, when I refresh the web client, even without calling the function API, **the function app will be killed**.
![image](https://user-images.githubusercontent.com/41713563/103977005-3380b180-51b3-11eb-8bbe-fdf3a4ad0762.png)
![image](https://user-images.githubusercontent.com/41713563/103977185-a427ce00-51b3-11eb-923b-860866d4efc3.png)

If I remove the Azure function extension, the task goes well without being killed. So what does azure function extension do to my function process? I don't even use `func` type task. I use `shell` type task. Isn't it supposed to be no impact whether or not I have installed Azure Function extension on my VS Code??

Please help! Thx!

**Comment by ejizba** [comment]
> So what does azure function extension do to my function process? I don't even use func type task. I use shell type task. Isn't it supposed to be no impact whether or not I have installed Azure Function extension on my VS Code??

Yeah I understand how that seems odd. The reason our extension is doing things here is because you are trying to debug, not _just_ run your function app. I would guess our extension sees that you tried to debug, failed to attach, and figure that you want us to clean up the task. There are two ways to get around this:
- Rather than debug, just run the "func: host start" task manually
    - From the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette):
    - ![Screen Shot 2021-01-11 at 4 38 19 PM](https://user-images.githubusercontent.com/11282622/104254365-7ea4f980-542b-11eb-91ce-d43ee687af4c.png)
    - ![Screen Shot 2021-01-11 at 4 38 25 PM](https://user-images.githubusercontent.com/11282622/104254378-8369ad80-542b-11eb-8f5a-882fc650a9aa.png)
- Set "azureFunctions.stopFuncTaskPostDebug" to false in your VS Code settings

If you could show me your `.vscode/launch.json` file that would also be helpful for further understanding

**Comment by dilin-MS** [comment]
Hi, This is my `.vscode/launch.json`. I am debugging my teams tab app with function backend, but I am not debugging function backend code. I just need function to be up and running. I don't want azure function extension to kill my function app because I am not debugging function app, just debugging my tab app. So will azure function extension kills function app even if the function app is not started by `func` type task??
```json
{
    "version": "1.0.0",
    "configurations": [
        {
            "name": "Local Debug Tab App(Teams Web Client)",
            "type": "pwa-msedge",
            "request": "launch",
            "url": "https://teams.microsoft.com/_#/l/app/e44d6ad3-6d4c-4fb2-8ccb-be6111fe820e?installAppPackage=true",
            "webRoot": "${workspaceFolder}",
            "preLaunchTask": "Start tab app, auth server and function app",
            "postDebugTask": "Terminate running tasks"
        }
    ]
}
```

While we do have another debugging flow to debug function backend. I am not sure whether setting `azureFunctions.stopFuncTaskPostDebug` to false will influence that flow.

Currently as a workaround, we will need to ask user to manually start function app **in terminal** instead of start the function app by task for them. 

The first method you mentioned, to start function by triggerring "Tasks: Run Task", does not work. Task-started  function app will be killed.

The second method works. With `azureFunctions.stopFuncTaskPostDebug` set to false, function app will not be killed. I guess this resolves our issue. 

Thanks!

**Comment by dilin-MS** [comment]
Hi @ejizba  will azure function extension fix this bug? Since the setting `azureFunctions.stopFuncTaskPostDebug` to false is just a workaround. Our user is possible to toggle the setting and thus break the debug process.
I think azure function should not try to kill function app when the function app process is not started by `func` type task. Thanks.

**Comment by ejizba** [comment]
Can you describe your scenario more? And why you felt the need to switch from a `func` task to a `shell` task? You say "and thus break the debug process", but to me it sounds like the debug process is already broken for you. We only stop the func process if VS Code detaches the debugger, which only happens if it can't connect (aka if it's "broken"). Am I correct in assuming you can't hit breakpoints in your function app?

**Comment by ejizba** [comment]
Sorry only saw the 2nd of two comments you posted.

> So will azure function extension kills function app even if the function app is not started by func type task??

Yes. We have users using both the `func` and `shell` tasks. People sometimes use the `shell` task because it allows a lot more customization, but they still want our debugging functionality (which allows them to hit breakpoints and cleans up the func task after they're done debugging). Your scenario sounds like an outlier - where you explicitly do _not_ want the help we provide so that you can debug your function app. We provide settings so that users with outlier scenarios can change behavior that we otherwise think helps the majority of our users.

> The first method you mentioned, to start function by triggerring "Tasks: Run Task", does not work. Task-started function app will be killed.

There's definitely a way to make this work. What are you doing after you run the task and when is the process killed? Are you pressing F5 at some point? If you see the debugger start and stop, it makes sense that we are stopping the func process.

It's also likely you could set up your project to debug _both_ the function app _and_ the tab app at the same time. That sounds like the "true" fix to me. I could help you figure this out if you want - it would be similar to how we instruct users to debug multiple function apps at the same time here: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

**Comment by dilin-MS** [comment]
The reason we choose to switch from `func` task to `shell` task is that we are trying yo get rid of azure function extension's killing our function app process... We can not prohibit user from installing azure function extension, and while function extension will kill the function app process, we try to switch to `shell` task hoping function process not get killed by function extension. From your reply, the function extension will still kill the function process.

Our scenario is that, we have a tab app, a auth server and a function app up and running, then we launch a edge client to *only* debug **the tab app**, **NOT** debug the **function app**. So no debug process will attach to function app. There will be a debug process attached to the edge client and we can debug tab app. 

In this situation, no debug process attached to function app but we still want the function app up and running to interact with our tab app. Function app serves as a backend of the tab app. But with azure function extension installed, it will kill our backend function process. How to get rid of it?


> There's definitely a way to make this work. What are you doing after you run the task and when is the process killed? Are you pressing F5 at some point? If you see the debugger start and stop, it makes sense that we are stopping the func process.

We use F5 to start tab app, auth server and launch edge client, but we remove the starting function app from preLaunchTask, then we use "run task" to start function app, then the function app get killed again during the debug process, which means our tab app, auth server and edge client is running well but function app just got killed with no action performed by user. If user tries refresh tab app, the function will be killed at once. 

The scenario you mention to debug *both* function and the tab app at the same time is our **another** local debug flow, we will support that, too. In that scenario function will not be killed since it has debugger attached to it. But we still need to support the debug scenario that *only* debug tab app with function running in the backend.

I think our main scenario is that we want to start a function app without any debug process attached to it, we want it to be a server and runs there. Just like user type `func host start` in their terminal. We do not want azure function extension to kill the process for us.

Thanks.

**Comment by ejizba** [comment]
I think the answer to this question is still just to use "azureFunctions.stopFuncTaskPostDebug". We also provide "azureFunctions.suppressProject" to ignore _all_ functionality from our extension for a specific folder if that's what you want.

Our debug behavior needs to apply to "shell" tasks for two reasons:
1. We have users that want to customize the "func" task and switching to "shell" is any easy way to do that, but they still want us to stop the debug session
2. We used "shell" for the first year or two of this extension, meaning plenty of old projects have "shell" hard-coded in their project and we need to maintain support

We provide settings like the ones mentioned to help users change the default behavior when they have an advanced or outlier scenario. I think this scenario fits squarely into that. We do have [this issue](https://github.com/microsoft/vscode-azurefunctions/issues/1064) to support a separate "start without debugging", but at the moment it hasn't gained enough traction and we may or may not address it.
