### ISSUE TITLE
[Suggestion] It would be better if add the "Read-only" next to "Functions" node after creating a function app with Linux OS and Consumption hosting plan

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2630]
**OS:** Mac
**Build Version:** 20210119.2

**Repro Steps:**

1. Create a Node.js function app with Linux OS and Consumption hosting plan.
2. Check the "Read-only" next to "Functions" node.

**Actual:**
Miss the "Read-only" next to "Functions" node.
![image](https://user-images.githubusercontent.com/62053665/105329346-051bc100-5c0c-11eb-8158-342566235c0b.png)

**Suggestion:**
It would be better if add the "Read-only" next to "Functions" node after creating the function app.

**More Info:**

1. The "Read-only" will appear after deploying a project to the function app.
2. This issue also reproduces for a Python/C# function with Linux OS and Consumption hosting plan.
3. This issue doesn't reproduce for a function app with Windows OS.

**Comment by ejizba** [comment]
This is by-design. There is an app setting like "WEBSITE_RUN_FROM_PACKAGE" that determines if an app is read-only and that isn't set right after the app is created. Also, people _can_ deploy without that and their app would not be read only (although I don't think that's common). Additionally, since they don't have any functions yet, there's no downside to the missing "read-only" label since there's nothing for them to attempt to modify/delete
