### ISSUE TITLE
Numbering of steps on VSCode are inconsistent depending on choices

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2643]
One example is here: 
![image](https://user-images.githubusercontent.com/6217333/105885873-55f63580-5fcf-11eb-9e5d-284edb986275.png)
![image](https://user-images.githubusercontent.com/6217333/105885880-58588f80-5fcf-11eb-8db8-420b6cc6ac25.png)
![image](https://user-images.githubusercontent.com/6217333/105885886-5989bc80-5fcf-11eb-9e30-a7a63a7ad3d6.png)

There are inconsistencies all over the place where sometimes they have numbered steps, then they don't have numbered steps, sometimes they have steps that go up and down based on choices/options, etc. I think removing them altogether would be best if there is no uniform way of doing things.

**Comment by ejizba** [comment]
> sometimes they have numbered steps, then they don't have numbered steps

We only ever hide the step count at the beginning of a wizard, before we have enough information to show an accurate count. If you see something to the contrary, please let us know the repro steps. In the case of "Create Function" we have a pretty good idea of the count after the user picks a template (i.e. Event Hub vs. Timer) and show the count then.

> sometimes they have steps that go up and down based on choices/options, etc.

Yes the step count fluctuates. We have had people tell us "That's a little weird", but it's always followed by "but actually it makes sense". If you select "Create New" vs. an existing item, you're going to have more steps because we need to know how to create the new item. It shouldn't go "down" unless you use the "back" button.

> I think removing them altogether would be best if there is no uniform way of doing things.

The step count should give users a rough idea of how long the wizard will be and we think it's worth it for that reason. One of the top reasons I like it is because I know that unless it says "5/5", "7/7", etc. - I have more prompts left and I have a chance to go back before I hit that final "enter". Finally, we think it's worth keeping because the count _is_ accurate based on their current choices, and we think accuracy is more important than the "uniformity" you described (always showing a count and never fluctuating that count).
