### ISSUE TITLE
No documentation around creating CosmosDB from VSC even though the extension is capable

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2646]
It's currently possible to create CosmosDB databases from the VSC extension but there aren't any docs around it.  Is this something that we should create? Could we provide steps in the extension information itself?

**Comment by ejizba** [comment]
From a docs perspective, we really only prioritize the "getting started" tutorials. For the more advanced scenarios (which would include CosmosDB IMO), it would take a decent amount of effort to author/maintain/etc. and at some point you have to hope your product is intuitive enough for users to explore and branch off themselves.

I think my feeling is - if the docs team wants to do it - great! But I wouldn't do it myself or push them to do it. I'll let @fiveisprime chime in before closing, though, since he interacts with docs people the most on our team

**Comment by nturinski** [comment]
Closing due to @fiveisprime never chiming in.
