### ISSUE TITLE
TypeScript fn with fn level auth uses "@azure/functions": "^1.0.2-beta2"

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurefunctions#2708]
I'm running into problems where the boilerplate packaging and code created by the extension produces an incorrect environment. I see then when my TypeScript types causes errors when running. 

![image](https://user-images.githubusercontent.com/41597107/109394182-82f17d00-78da-11eb-8400-2fb896f031df.png)

When I investigated why the TypeScript boilerplate doesn't understand TypeScript types, I realized the version of the functions package is still on a beta when npm shows that as 2 years old. 

![image](https://user-images.githubusercontent.com/41597107/109394225-c2b86480-78da-11eb-9c7d-62794c667227.png)

Why is the extension installing a package that is 2 years out of date?

**Comment by ejizba** [comment]
We use a caret (`^`) in package.json when specifying the version for that package, which means you'll get any `1.*.*` version above `1.0.2-beta2`. For example, when I do `npm install` from a fresh project, I see the latest version (`1.2.3`) referenced in my package-lock.json. By default, `npm` uses the latest allowed version unless you already have a `package-lock.json` file in your workspace.

I can update the default version we put down because I agree it's confusing that it's referencing a "beta", but all that does is affect the _minimum_ version you can use, not the _exact_ version.

**Comment by diberry** [comment]
The current minimum version is old old - can the minimum version keep pace with the extension itself? Why would we update the vscode extension functionality and not give the customer the option of using the latest functionality for functions themselves?

**Comment by ejizba** [comment]
There would be no functional difference if we kept the minimum version up-to-date because `npm` already installs the latest version by default. Can you try creating a new project, do `npm install` and check the version of `@azure/functions` in `package-lock.json`? It should reference "1.2.3"

**Comment by diberry** [comment]
I just checked, while the package.json does say beta, the actual version node_modules is that latest. While this is superconfusing, it isn't broken.

**Comment by ejizba** [comment]
Cool - yeah we'll get rid of "beta" to reduce some of the confusion.
