### ISSUE TITLE
Copy function key

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurefunctions#2710]
If I create a function with auth at the function level, do I have to leave the extension to see the key? I'll need it to test with my client.

**Comment by ejizba** [comment]
We don't have that feature, no. We do allow people to test using either "Copy Function URL" (which will have the key inside it) or "Execute Function Now" (which will use the key under the covers):
![Screen Shot 2021-03-02 at 11 17 45 AM](https://user-images.githubusercontent.com/11282622/109702366-fdbfcf80-7b48-11eb-9914-6fb31eb08916.png)


Let us know if that's sufficient and we'll close the issue, otherwise we'll keep it open as a feature request. Just because I'm curious: what do you use to test?

**Comment by diberry** [comment]
Please leave it open as a feature request. I use [curl to test](https://github.com/Azure-Samples/js-e2e/blob/main/apps/azure-functions-http-trigger-typescript/readme.md#test-local-functions).
