### ISSUE TITLE
Stream logs option at the end of VSCode deployment redirects to output panel without starting the logs stream

### ISSUE THREAD

**Issue by sinedied** [microsoft/vscode-azurefunctions#2717]
After deploying an Azure Functions using the VS Code extension, the notification that appears at the end of the deploying shows the option to stream logs. Click on this option redirects to the log output panel, but log streaming does not start even after waiting some time (> 1 min). You need to go to the functions panel and explicitly start log streaming to see logs appearing.

I expected that after clicking on the "Stream logs" button the logs would start streaming immediately without having to start it manually.

This was tested using JS Functions.

Original internal backlog issue: https://dev.azure.com/azuretracking/Azure%20tracking/_workitems/edit/1722

**Comment by ejizba** [comment]
I was able to reproduce this a while ago and if I remember correctly the logs were streaming under the covers, but the VS Code output channel wasn't displaying what we sent it for some reason. When I tried today, it was no longer reproducing for me. My suspicion is that it may have been a VS Code bug which has been fixed in the meantime (for example, maybe they had a timing issue where logs weren't displayed immediately after an output channel was created)
