### ISSUE TITLE
No stack trace displayed in VSCode log stream when the function throws an exception

### ISSUE THREAD

**Issue by sinedied** [microsoft/vscode-azurefunctions#2718]
When streaming logs in VS Code, if my function throws and exception, the stack trace is not displayed in the logs, making it difficult to debug the issue:
![image](https://user-images.githubusercontent.com/593151/109777421-fa3d4e80-7c03-11eb-9d5e-1472b5a2f2b5.png)

Note that it might not be directly related to the extension, but more likely to the core tools.
Tested with JS Functions.

Original internal backlog issue: https://dev.azure.com/azuretracking/Azure%20tracking/_workitems/edit/1723

**Comment by ejizba** [comment]
Did a bit of testing on this. If I do `throw 'error';`, I can repro the above:

![Screen Shot 2021-05-14 at 4 35 16 PM](https://user-images.githubusercontent.com/11282622/118341087-b9e73000-b4d2-11eb-89d7-99aadafa6294.png)

But if I do `throw new Error('test');` I see the stack:

![Screen Shot 2021-05-14 at 4 30 42 PM](https://user-images.githubusercontent.com/11282622/118341110-c7041f00-b4d2-11eb-84c7-baa30c7f05a5.png)

Since `new Error` is the recommended/common way of doing this and since any fix would need to be in the core tools (not us), going to close this issue
