### ISSUE TITLE
Pop up the notification "Executed function..." when clicking "execute function now" for the C# project during debugging another project in the other window

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2732]
**OS:** All
**Build Version:** 20210304.27

**Repro Steps:**

1. Create a C# project with "HttpTrigger" function -> Open it in VS Code(**Window 1**) -> Restore.
2. Create a JavaScript project with "HttpTrigger" function -> Open it with a new window(**Window 2**) -> Debug.
3. Select "Execute Function Now" for "HttpTrigger" function in the local project tree view(**Window 1**).
3. Check the result.

**Expect:**
Pop up an error "Failed to connect...".
![Screen Shot 2021-03-05 at 4 40 57 PM](https://user-images.githubusercontent.com/62053665/110096278-b51e4580-7dd8-11eb-9fb9-ae2c9a3260b8.png)

**Actual:**
Pop up the notification "Executed function...".
![Screen Shot 2021-03-05 at 5 55 19 PM](https://user-images.githubusercontent.com/62053665/110099853-bf424300-7ddc-11eb-8feb-e8a992e854ff.png)

**More Info:**
This issue also reproduces for other projects.

**Comment by ejizba** [comment]
Most projects use the same base url when running locally (`http://localhost:7071/`), so it makes sense that "Execute Function Now" would work if the function is named the same. I understand there is a bit of confusion here and I think the only thing we could do is try to detect if that particular window is running and throw an error during "Execute Function Now" if it's not. However, I don't think that's worth it because users might be intentionally running `func host start` outside VS Code (maybe in a terminal if they don't care about debugging), so I don't want to risk blocking them from this functionality.
