### ISSUE TITLE
"azureFunctions.defaultFunctionAppToDeploy" Is Ignored Without Warning

### ISSUE THREAD

**Issue by superelitist** [microsoft/vscode-azurefunctions#2789]
### Expected Behavior: 
1. Edit setting in GUI or add to (workspace) `settings.json`:
`"azureFunctions.defaultFunctionAppToDeploy": "/subscriptions/<uuid>/resourceGroups/<group>/providers/Microsoft.Web/sites/<app_name>"`
2. Right click on Function App folder, choose "Deploy to Function App..."
3. VS Code will deploy to the indicated Function App without asking which Function App to deploy to.

### Observed Behavior:
1. As above.
2. As above.
3. The setting is **silently removed(!)** from `settings.json`, and the user is asked which Function App to deploy to.

### Additional Information:
Thinking that maybe it's some sort of bizarre field validation, I have attempted several variations of "full Azure Id" (*although there doesn't seem to be an official consensus on what this means, I believe it's the same as the "Resource ID" as listed in the Azure portal under Properties*). I also tried the URL, and just the short name of the app. The behavior is the same in all cases. I also tried placing the setting in the general `settings.json`--it doesn't get removed, but it's ignored anyway.

I'm not even sure if this is a bug with the extension, or with VS Code--but with no errors or warnings it's difficult to understand what is even happening. The setting simply disappears without any fanfare, which is... unsettling to say the least.

Versions:
VS Code: 1.55.2
Azure Functions Extension: 1.3.0

**Comment by ejizba** [comment]
It appears we remove the setting if we can't find an app matching the id, which I agree is not great haha. We should at least show a warning or something

You are correct that it should be the "resource id". I believe our logic is case-sensitive, so that could be the problem here. As a workaround, I would right click on your function app, do "View Properties", and copy the id exactly as shown - hopefully that has the right casing.

**Comment by superelitist** [comment]
Cheers! Thanks for the feedback.

I suppose there must have been some difference, because copying the id from 'View Properties' almost worked--but now it pops up a window asking, "Initialize project for use with VS Code?", which isn't quite right, because my azure functions folder is in a subpath of my repo root--I think the correct setting to identify a project subpath is `"azureFunctions.projectSubpath": "./<folder_in_repo>/<subfolder>"`, but setting that doesn't appear to mitigate this dialog. Maybe my syntax is incorrect?

**Comment by ejizba** [comment]
That setting is correct, but we need other settings as well, like "azureFunctions.projectLanguage" in order to deploy. I would suggest you let "Initialize project for use with VS Code?" do it's thing. It _should_ detect that your project is in the subfolder and adjust the new settings accordingly. All the changes should be in the `.vscode` folder, so assuming you track that in git (which we recommend), you can double check what we changed after it happens
