### ISSUE TITLE
Visual Code - Function project creation error 

### ISSUE THREAD

**Issue by guruskumar** [microsoft/vscode-azurefunctions#2802]
Refer: Visual Code - Function project creation error #2788
creating new one because old one closed without  resolution.
---

In Visual Code
Created new workspace, File new window
Selected the Function, Create NEW function Project
Selected local folder  language as C#  .net core 3
Below error to create functions in VS code,
Failed to find "autorest" | Extension needs AutoRest to generate a function app from an OpenAPI specification. Click "Learn more" for more details on installation steps.

----

Please find below details and attached error logs while creating the azure function in VS code.
• Version of the Functions extension : v1.3.0
• Version of VS Code :1.52.1
• OS : Windows 10
• Versions of .NET sdk installed on your machine: 5.0.101
• Any logs you see from the "Azure Functions" output window : attached logs
you can install autorest from the "Learn more" link in the error : we can’t install software’s from open source.
[functionError.docx](https://github.com/microsoft/vscode-azurefunctions/files/6479037/functionError.docx)
[Functionerror_log.txt](https://github.com/microsoft/vscode-azurefunctions/files/6479038/Functionerror_log.txt)

**Comment by ejizba** [comment]
If you select .NET Core 3, you must have v3 of the .NET Sdk installed (not just "5.0.101" as you mentioned).

If you're having problems with the templates another thing you can try is add this to your VS Code settings:
> "azureFunctions.showReloadTemplates": true

And the next time you try to create a function, click the "Reload templates" option to clear any cached info
![Screen Shot 2021-05-17 at 11 47 44 AM](https://user-images.githubusercontent.com/11282622/118540760-bdaec880-b705-11eb-822b-05feb715d2f2.png)

**Comment by guruskumar** [comment]
[FunctionError.docx](https://github.com/microsoft/vscode-azurefunctions/files/6502417/FunctionError.docx)
Attached with screenshots, still we get error

**Comment by guruskumar** [comment]
reopened, its closed accidently.

**Comment by guruskumar** [comment]
reopen

**Comment by ejizba** [comment]
I'm sorry, but this issue just does not have clear enough steps for us to reproduce the problem or investigate any further. 

If you still want help, please start over with a new issue and try your entire scenario again using the latest extension. As you try the scenario again, describe explicit steps you are taking, any logs along the way (From the "Azure Functions" output window), and the "expected" vs. "actual" behavior. A few notes:
- If you do not want to create an "OpenAPI" function, do not include that in your steps and do not mention any "OpenAPI" error because it's unrelated to your "expected" behavior
- Please do not attach docx or .txt files. Add the logs/images directly into the GitHub issue
- Do not refer to previous issues which also did not have enough information. The issue on GitHub should be standalone with all of the information we need
- See https://aka.ms/azcodeissuereporting for more information.
