### ISSUE TITLE
Enable remote debugging of functions from local VS Code w/o creating a security problem

### ISSUE THREAD

**Issue by seajhawk** [microsoft/vscode-azurefunctions#2843]
Customer (Jason) uses Azure Functions extensively. 
He loves to run them locally and debug them, but wants to be able to debug functions deployed to Azure without creating a security problem by opening additional ports, etc.

**Comment by ejizba** [comment]
I do not think it is possible to remote debug without opening up a port - we have to get the debugging information somehow. In addition to your security concerns, remote debugging can also negatively affect performance of your app. For those reasons, I would only recommend you remote debug on test apps instead of production apps.
