### ISSUE TITLE
F5 doesn't listen for changes

### ISSUE THREAD

**Issue by ethanroday** [Microsoft/vscode-azurefunctions#285]
Steps to repro:
1. Create a new project using the "Create New Project" command
2. Create a new function with the "Create Function" command
3. F5 to start debugging
4. Make a code change

Expected result:
The project rebuilds, the function host detects the change, and the code change comes through.

Actual result:
Nothing happens, and restarting the debugger (Ctrl + Shift + F5) does not pick up the change either. Getting the change to be recognized requires disconnecting and manually reattaching the debugger.

Coming from previous experience with Function Apps written in C# Script (where the function host just detects changes automatically), this seems like a downgrade of the developer experience.

**Comment by EricJizbaMSFT** [comment]
Closing this as debug experience has changed a lot since it was originally opened and I think this is covered by other bugs.

We still don't support "edit and continue" for JavaScript, but that's due to a bug in the functions host tracked here: https://github.com/Microsoft/vscode-azurefunctions/issues/781

We don't officially do much with C# Script and instead drive people to C# class libraries, which will never pick up changes automatically due to compilation. Restarting the debugger also doesn't work - tracked here: https://github.com/Microsoft/vscode-azurefunctions/issues/756
