### ISSUE TITLE
Add setting to show deprecated stacks

### ISSUE THREAD

**Issue by nate-alex** [microsoft/vscode-azurefunctions#2855]
Does this occur consistently?  Yes
Repro steps:

Starting ~1 day ago, deploying new functions no longer gave me the option to select node.js 10 LTS. I'm not sure what has changed and caused this issue, but functions will not run on the runtime stack that still remains (node.js 8 LTS). Deploying locally I was able to test the API yesterday, but after uninstalling and reinstalling nodejs, that appears to be broken now too.

1. Click on deploy to function app
2. Create new function app in azure
3. Type in new function app name
4. ISelect a runtime stack. Only Node.js 8 LTS shows up whereas previously Node.js 8 and 10 were options. Deploying with node 10 has always worked fine for me, but version 8 is not compatible.  

Version: 0.4.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

**Comment by ejizba** [comment]
@nate-alex, support for Node.js 10 turned end of life on April 30th, 2021, see here: https://github.com/nodejs/Release. As such, support in Azure has been deprecated and the option removed in VS Code. Node 8 is also deprecated and I'm surprised it's still showing up (we call an Azure API to get the list, so it's not 100% up to us what gets displayed).

My recommendation is to switch to Azure Functions v3, which supports Node.js v12 and v14. In VS Code, you can do that by changing "azureFunctions.projectRuntime" in your `.vscode/settings.json` file to "~3" instead of "~2". You should update the version of your func cli to match, if you have it installed locally. Finally, the breaking changes for JavaScript functions were minimal in v2->v3, but regardless I recommend taking a look at the docs here: https://docs.microsoft.com/azure/azure-functions/functions-versions#breaking-changes-between-2x-and-3x

We currently do not have any way to show deprecated stacks in VS Code and I don't think it's possible in the portal. You might be able to create a Node 10 app with the az cli, but I haven't tried it. I can potentially add a setting to show deprecated stacks, but you would have to install an insiders build of our extension to get that and I can't guarantee that Node.js 10 will keep working in Azure
