### ISSUE TITLE
Allow multiple functions per workspace folder

### ISSUE THREAD

**Issue by jesperkristensen** [microsoft/vscode-azurefunctions#2862]
I have a repo in this structure:
```
src/
     Shared/ -- c# class library with shared functionality
     SomeFunctionApp/ -- a function app that has a project reference to Shared
     AnotherFunctionApp/ -- a function app that has a project reference to Shared
```

I want to configure VS Code to debug both of these function apps (I don't need to run both at the same time), while still seeing and debugging the Shared project. This does not seem to work because it looks like the VS Code extension assumes there is only one function app per workspace folder.

**Comment by ejizba** [comment]
We have some guidance here which may or may not be helpful for your case: https://github.com/microsoft/vscode-azurefunctions/wiki/Multiple-function-projects

Otherwise, please expand on this quote a little bit:

> This does not seem to work because it looks like the VS Code extension assumes there is only one function app per workspace folder.

What is an example scenario where we are assuming there is only one project? And what would be your preferred behavior in that case?

**Comment by jesperkristensen** [comment]
Thanks. Option 2 described on that page seems to work. I had not thought about it because I assumed each workspace root would work independently. It does make navigation significantly more cluttered because now I have 50 root folders in my workspace instead of 20, and a large fraction of files are now duplicated (once in the workspace root for the parent folder, and once in the workspace root for the azure functions folder)
