### ISSUE TITLE
IoTHub function deployment: "receiverConnectionString" not properly set in application settings

### ISSUE THREAD

**Issue by pchevallier** [microsoft/vscode-azurefunctions#2867]
While deploying to Azure from VB, I kept seeing this error message in the deploying log
`Microsoft.Azure.WebJobs.Host: Error indexing method 'IoTHub_EventHub'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. (Parameter 'receiverConnectionString').`
And no messages is received from IoT Hub Azure function 

I had the following file contents:
Function file: IoTHub_EventHub.cs:
```
[FunctionName("IoTHub_EventHub")]
        public static void Run([IoTHubTrigger("samples-workitems", Connection = "IoTHubTriggerConnection", ConsumerGroup= "trucklocation")]EventData message, ILogger log)
        {

```

The connection string was correctly entered into the config file: local.settings.json
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=xxxxxxxxxx;AccountKey=XXXXXXXXXXXXXXXXXXX;EndpointSuffix=core.windows.net",
    "IoTHubTriggerConnection": "Endpoint=sb://ihsuprodytres016dednamespace.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=XXXXXXXXXXXXX;EntityPath=iothub-ehub-xxxxxxxxxxxxx",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```
Unfortunately, the variable wasn't taken into account. 
### Environment: 

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RootNamespace>xxxxxxx_functions</RootNamespace>
  </PropertyGroup>

```
### Visual Basic:
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (1 wk ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

### dotnet
.NET Core SDK (reflecting any global.json):
 Version:   3.1.408
 Commit:    88530ea5c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.408/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

+++++++++++++++++++++++++++++++++++ Diagnostic +++++++++++++++++++++++++++++++++
After some search, it turned out, the _IoTHubTriggerConnection_ was not being created in the Azure Function environment parameters during deployment which caused the error message above.
+++++++++++++++++++++++++++++++++++ ++++++++ +++++++++++++++++++++++++++++++++

### WORKAROUND: 
In order to work around this issue, manually enter its value on the portal: 

![image](https://user-images.githubusercontent.com/20049529/123544691-7105d680-d722-11eb-8fae-6c8662188f1d.png)

And messages are finally appearing on the function side. 

This is just a work-around and cannot be a final fix for production level deployment in CI/CD 
This should be done automatically during deployment instead.

**Comment by ejizba** [comment]
After you deploy your project, the confirmation notification has an option to "Upload Settings"
<img width="547" alt="Screen Shot 2021-06-28 at 10 22 33 AM" src="https://user-images.githubusercontent.com/11282622/123678155-d0371a00-d7fa-11eb-915f-f1690e571d90.png">

You may also upload or modify settings at any time in the Functions view:
<img width="221" alt="Screen Shot 2021-06-28 at 10 23 30 AM" src="https://user-images.githubusercontent.com/11282622/123678216-e6dd7100-d7fa-11eb-8ac8-fd7469c95382.png">

We do not upload automatically because the settings people use locally are often for testing purposes only and they use different values on the deployed app. Deploying from VS Code is a quick and easy way to get something running in Azure, but if you're looking for "production level deployment in CI/CD" I would recommend using Azure Pipelines or GitHub Actions for true CI/CD.
