### ISSUE TITLE
[Unstable] The debugging stops automatically when deploying the project which is debugging to a Node.js web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2952]
**OS:** Win10
**Build Version:** 20210905.1
**Regression:** Not a regression

**Repro Steps:**

1. Open an empty folder in VS Code insider-> Create a project with TypeScript language and HTTP trigger function in the opend folder -> F5.
2. Deploy the new created project to a Node.js web app during debugging.
3. Check whether the debugging stops automatically.

**Expect:**
The debugging does not stop automatically.

**Actual:**
The debugging stops automatically.
![ts](https://user-images.githubusercontent.com/62053665/132292443-6290cbdf-d8e5-434b-9049-baa7307a9b87.gif)

**Comment by ejizba** [comment]
This is likely a race condition related to the preLaunchTask (for debugging) and preDeployTask (for deploying). I would actually expect both to work at the same time, but it makes sense that we run into problems since the preDeployTask is "npm prune" which removes dev dependencies. Closing this one because it would be too difficult to make both work at the same time
