### ISSUE TITLE
Default a function app name at creation

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurefunctions#3013]
![image](https://user-images.githubusercontent.com/3982077/144106178-37596ac8-e0fc-4ac0-b1d4-772a023e0a42.png)

Perhaps derive this from folder name or remote git repo name, and coming up with a way to make sure it's globally unique.

**Comment by nturinski** [comment]
Was there a user study that prompted this issue?  If the issue is confusion about the first step, how about a placeholder text that says: `Function name` in the input box?

Checking to see if an app name is unique can be a lengthy process (depending on connection) and would hurt overall performance of creation.  Especially since this is the very first step, any delay after clicking the + seems to be a really negative UX to me.
