### ISSUE TITLE
The function name in the opened file changes to "HttpTrigger_1" when creating a function with name "HttpTrigger-1"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3017]
**OS:** Win10
**Build Version:** 20211203.8
**Regression:** Not a regression

**Repro Steps:**

1. Open an empty folder in VS Code -> Create a C# project with function **HttpTrigger-1**.
2. Click the `HttpTrigger-1.cs` file.
3. Check whether the function name in the opend file is **HttpTrigger-1**.

**Expect:**
The function name in the opened file is **HttpTrigger-1**.

**Actual:**
The function name in the opened file is **HttpTrigger_1**.
![image](https://user-images.githubusercontent.com/62053665/144827408-f881a71d-628a-47e1-9c22-bc627fc383f0.png)

**More Info:**
This issue doesn't reproduce for other language projects.

**Comment by v-mengwe** [comment]
Deploy the project to a function app -> Expand the function node of function app -> The function also shows "**HttpTrigger_1**".
This issue also reproduces for TimerTrigger function.
![image](https://user-images.githubusercontent.com/62053665/145974857-76f713e5-87f6-4f5a-8516-8aba19acf340.png)

**Comment by nturinski** [comment]
I believe that this is because of [this](https://stackoverflow.com/questions/12216225/how-do-i-declare-a-variable-with-hyphen-on-it#:~:text=However%20c%23%20does%20not%20let%20you%20use%20hyphens%20in%20names%20under%20any%20circumstances%20because%20that%20character%20is%20used%20for%20the%20unary%20negation%20and%20binary%20subtraction%20sub%20operator.).  I think we can close this as the templates is fixing this error for us.
