### ISSUE TITLE
Deployment on Azure function in Vscode

### ISSUE THREAD

**Issue by nccharles250** [microsoft/vscode-azurefunctions#3190]
Does this occur consistently? 
The issue is:

1. Can't find a deployment option in vscode

Version: 1.7.0
OS: Linux
OS Release: 5.13.0-44-generic
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

**Comment by almmechanics** [comment]
All my Azure Function tool bars have disappeared as of the latest update. The options are available in the command pallette but not in the user interface.

All Azure Tools have now disappeared as can be seen below:

![vscodebug](https://user-images.githubusercontent.com/20181453/170218740-46323d3c-12d9-4188-a575-a7b296ea798b.png)



Version: 1.7.0
OS: Windows 
OS Release: Version	10.0.19044 Build 19044
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

**Comment by nccharles250** [comment]
Exactly the same as mine @almmechanics

**Comment by matkozak** [comment]
Same here. Comes back after downgrading to 1.6.2.

**Comment by bwateratmsft** [comment]
This is intentional, the new options and views will be in the Resources and Workspace view. We have combined most of the Azure views into one under the Resources view. You can read more here:
- https://aka.ms/AzCode/AppCentric
- https://github.com/microsoft/vscode-azureresourcegroups/wiki/Introducing-the-redesigned-Azure-extensions-for-VS-Code

**Comment by alexweininger** [comment]
@nccharles250 Don't worry! We're going to add the deploy button in the next release #3192. Sorry for the inconvenience.
