### ISSUE TITLE
An error occurs when debugging a TypeScript project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3199]
**OS:** All
**Build Version:** 20220526.13

**Repro Steps:**
1. Create a TypeScript project with HttpTrigger function.
2. Debug it.
3. Check whether succeeds to debug the project or not.

**Expect:**
Succeed to debug a TypeScript project.

**Actual:**
An error occurs when debugging a TypeScript project.
![image](https://user-images.githubusercontent.com/45614674/170675176-80da179c-924d-4f32-bff5-7990eb42ae33.png)

**More Info:**
This issue does not reproduce after executing command "npm i --save-dev @types/node".

**Comment by alexweininger** [comment]
This reproduces on v1.7.1 also

**Comment by ejizba** [comment]
This was due to a recent release of the "@azure/functions" types package which references "Buffer" for the first time. Filed this issue to investigate if we can fix on the types side, but I'm not optimistic: https://github.com/Azure/azure-functions-nodejs-worker/issues/587

The "template" for TypeScript projects is owned by the VS Code extension, so it might be on the extension to address. We went back and forth on whether "@types/node" should be included in TypeScript projects by default in the past (for example [here](https://github.com/microsoft/vscode-azurefunctions/pull/1745)), but that was when `@azure/functions` didn't reference any node types. The main problem is knowing which version to pick.

**Comment by alexweininger** [comment]
A [postinstall script](https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts) could check the installed node version and install the corresponding `@types/node` package.

**Comment by ejizba** [comment]
Do you have examples of other types packages doing that? I don't really want to re-invent the wheel here as I think it's a very common thing for types packages to reference node types. I'd rather just follow what other popular packages are doing

**Comment by alexweininger** [comment]
> Do you have examples of other types packages doing that?

Yeah I don't have any examples. 😄

I just tested out enabling the `skipLibCheck` option in the `tsconfig.json` and it makes the error go away. Maybe the template could enable that by default?

I know that's not optimal, but [TypeScript is exploring better options for skipLibCheck](https://github.com/microsoft/TypeScript/issues/30511#issuecomment-1103259948).

**Comment by ejizba** [comment]
@alexweininger Would you be fine if we add `@types/node` to the default template in VS Code? I think that's the most common solution. For example if I do `yo code` for a new VS Code extension it'll have `@types/node` set to `16.x`. It's a bit more complicated for Functions because of the version matrix, but I'd probably do some mix of trying to match the user's local version and using known versions that are supported for Functions.

If you're fine with the change, I'm happy to submit a PR myself. I will have to make the same change in core tools as well

**Comment by alexweininger** [comment]
Sounds good to me 👍

**Comment by v-ruizh** [comment]
Verified this issue on the extension build 20220606.8, it has been fixed.

**Comment by alexweininger** [comment]
Thank you @v-ruizh!
