### ISSUE TITLE
[Suggestion] It would be better to add support for python 3.10 when creating project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3201]
**OS:** All
**Build Version:** 20220526.13

**Repro Steps:**
1. Execute creating a python project command.
2. Check whether there is a "python 3.10.X" interpreter option when creating a python project or not.

**Actual:**
There is no "python 3.10.X" interpreter option when creating a python project.
![image](https://user-images.githubusercontent.com/45614674/170681613-eb9af6f2-e78e-402d-881d-23e5dcb24e8a.png)

**Suggestion:**
It would be better to add support for python 3.10 when creating project.

**More Info:**
There is a python 3.10 option when creating a Function App.
![image](https://user-images.githubusercontent.com/45614674/170681479-02ea91b0-0eee-4e19-8c5a-de4dd6d72a81.png)

**Comment by alexweininger** [comment]
For some reason, the "Python 3.10 (Preview)" item is not present for us. Could you try again and check if it's still there?

**Comment by v-ruizh** [comment]
@alexweininger There is a setting "azureFunctions.showHiddenStacks" for Function App. The "Python 3.10 (Preview)" item will be present if you set it.
![image](https://user-images.githubusercontent.com/45614674/172975495-36759c70-d83c-48e0-b5fc-22b1ebbf81f5.png)

**Comment by ejizba** [comment]
The Python team is actively working on supporting 3.10, which is why you see it in some places but not others. I tried to find an issue for tracking purposes in their repo here, but didn't find one: https://github.com/Azure/azure-functions-python-worker

You'll have to ask them for the schedule - I can't remember if a new python version requires changes in the VS Code extension or not.
