### ISSUE TITLE
Subscription not found when creating function app with trial account

### ISSUE THREAD

**Issue by scook1802** [microsoft/vscode-azurefunctions#3269]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: SubscriptionNotFound
Error Message: Subscription redacted:id was not found.

Version: 1.7.4
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1823131
deserializeResponseBody extension.bundle.js:2:1823862
```

</details>

**Comment by WallyWally12** [comment]
> Does this occur consistently? Repro steps:
> 
> 
> Action: azureFunctions.createFunctionApp Error type: SubscriptionNotFound Error Message: Subscription redacted:id was not found.
> 
> Version: 1.7.4 OS: win32 OS Release: 10.0.22000 Product: Visual Studio Code Product Version: 1.69.2 Language: en
> 
> Call Stack

Same here (new user)!

**Comment by nturinski** [comment]
Are you guys using student accounts by chance?

**Comment by WallyWally12** [comment]
Hi,

No, just normal accounts in trial mode with the 200 dollar allowance. I even used two different accounts, but both fail.
I was only able to upload to an App Service, however I’m now deviating from the Microsoft training, so that not ideal.


Best regards, Met vriendelijke groet,

Ingmar Waller
Solution Architect & Product owner ORTEC Routing & Dispatch

+31 (0)6 1313 7176 | ***@***.******@***.***> | LinkedIn<http://www.linkedin.com/in/ingmarwaller> | ortec.com<https://ortec.com/>

**Comment by MJSanfelippo** [comment]
Hi, I am running into this too. I created a new Azure subscription on my personal account with my $150/month free Azure credits as MSFT employee. I am following [this guide](https://docs.microsoft.com/en-us/learn/modules/develop-azure-functions/5-create-function-visual-studio-code) and running into this same issue.

**Comment by raff-run** [comment]
Having the exact same problem here. Just created a 200 dollar free acount with this my email.

**Comment by BartoszCki** [comment]
Same as described by @raff-run

**Comment by minaelee** [comment]
I've tested this and found it reproducible. With a previously existing account, I could create a function app through VS Code with no problems. I created a new Azure account, signed out in VS Code from the old one, signed in with the new. Then, no matter what region I chose, I got the Subscription ... not found error when trying to create a new function app. 

The only way I could get past this was to create a new function app through the Azure portal. Even then, there are problems. New function apps created using new Azure accounts do not have the option to add storage accounts to the function app. I don't know why this is, but perhaps has something to do with the new version of storage accounts that was released recently. 

What happens when you try to use the Azure extension to deploy a function to a function app created without any storage is this:

```
1:43:57 PM AzureFnAppTest2022: Creating placeholder blob for linux consumption function app...
1:43:57 PM AzureFnAppTest2022: Malformed SCM_RUN_FROM_PACKAGE when uploading built content.
1:43:57 PM AzureFnAppTest2022: Generating summary of Oryx build
1:43:57 PM AzureFnAppTest2022: Deployment Log file does not exist in /tmp/oryx-build.log
1:43:57 PM AzureFnAppTest2022: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
1:43:57 PM AzureFnAppTest2022: Deployment Failed. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
1:44:01 PM AzureFnAppTest2022: Deployment failed.
```

What I did to get past this:
Add the storage account manually. You can do this in the Azure portal by going to **Storage accounts**, and creating one with default options.
Then find the **Access key** for that storage account and copy the **connection string**. There are two access keys, I used the first one.
Then go to the function app's **Configuration** panel, and add a new **Application Setting** with the **name** of **AzureWebJobsStorage** and the **value** of the **connection string**, then click **Save**. Make sure to click Save! 

After this, deploying a function to that function app from the VS Code Azure extension worked for me.

**Comment by BrettGoreham** [comment]
+1 to this.
this not working effects AZ-204 course as the described way to start a function doesnt work currently

**Comment by minaelee** [comment]
ALL of the ways that the Azure docs and tutorials describe to add a function app do not work currently for any new subscribers due to this bug. Including the instructions provided in the Azure portal when you go to create a function. That's a pretty big deal and I wish more attention would be paid to this.

**Comment by nturinski** [comment]
Hi @minaelee 

Thanks for detailed explanation. This was helpful for diagnosing the issue. I have a PR opened that should resolve this issue.

I have a custom VSIX here: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=52115&view=artifacts&pathAsName=false&type=publishedArtifacts

But hopefully we will release this soon so that the tutorials will work again.

**Comment by minaelee** [comment]
@nturinski Fantastic, thank you!!

**Comment by minaelee** [comment]
Is it intended that function apps should be able to be created in the extension (without the "Subscription ... was not found") but at this time? Or is the workaround of creating a storage account in the portal still necessary for the time being?

(I'm finding that the latter is true - and also that as long as a storage account has been previously created on the subscription, doesn't matter the resource group, a new function app will create through the extension properly.)

**Comment by nturinski** [comment]
Hi @minaelee

You would have to install the custom build that I linked for the fix to be patched in.  However, we should be releasing the update shortly (v1.8.0) that will include the fix as well. I anticipate that we will get that released before EOD!

Until then, the workaround will be necessary.

**Comment by nturinski** [comment]
Just wanted to let you know that the fix should now be live!

**Comment by minaelee** [comment]
Just wanted to let you know that I tested again.
Azure wasn't happy with me creating so many new accounts, so I had to use the same one as previously (created _after_ the bug started happening) but deleted all resource groups on it except the DefaultResourceGroup-CUS one, and the storage account I'd created on it, to hopefully mimic a new account.
Uninstalled Azure Functions extension and reinstalled. Went through all the steps to create a function app and deploy a function - works perfectly, just as before! Thanks again!
