### ISSUE TITLE
Expose new Durable Functions backend options 

### ISSUE THREAD

**Issue by lilyjma** [microsoft/vscode-azurefunctions#3272]
Netherite (which uses Event Hubs and Azure Storage) and SQL should be available as storage providers when using Durable Functions. The default option currently is Azure Storage.

**Comment by lilyjma** [comment]
(this is a feature request, but I couldn't add a label because of lack of permission)

**Comment by nturinski** [comment]
Hi @lilyjma

Could you please share more information about this feature request?  We would need to know what the expected UX/UI design would be. Would we need to list user's Netherite and SQL connection strings, for example?

How are these normally hooked into Durable Functions?  Is there any documentation that you could provide so that we could understand this scenario better?

**Comment by alexweininger** [comment]
Closing to merge with #2956
