### ISSUE TITLE
There is no function in Functions node after deploying a Python (New Model Preview) project to a function app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3295]
**OS:** Win 10/Ubuntu 22.04
**Build Version:** 20220819.8
**VS Code Version-insiders:** 1.71.0-insider

Repro Steps:
1. Create and open a Python (New Model Preview) project.
2. Uncomment the commented code block in function_app.py.
3. Add a new function "TimeTrigger" append to function_app.py.
4. Deploy this project to a Python Function App.
5. Check whether there are functions in Functions node after deployment.

**Expect:**
There are functions in Functions node.

**Actual:**
There is no function in Functions node.
![image](https://user-images.githubusercontent.com/45614674/186146810-014ff3a8-1ab0-4a42-8147-e5aebffd0b89.png)

**Comment by philliphoff** [comment]
I *think* this is an issue where the Azure Functions App host doesn't have a version of (or isn't configured to use a version of) the core tooling that supports PyStein-based projects.

**Comment by philliphoff** [comment]
A couple of potential causes:

- Currently, only the "Premium" tier of Azure Function App uses a runtime that supports PyStein.  The "consumptive" tier *did*, but was recently rolled back to an earlier version due to a regression.
- PyStein applications require the `EnableWorkerIndexing` feature flag be set in the `AzureWebJobsFeatureFlags` application setting.  This value is set by the extension for local debugging, but also needs to be set before/after deployment in order for the runtime to properly find the functions.  This should be necessary only during the Preview period.  I opened issue #3310 to see if we can automate that during deployment as well.

@v-ruizh Let me know if this helps deployments succeeding.

**Comment by v-ruizh** [comment]
@philliphoff Thanks for your update. This issue can be fixed after adding the setting "AzureWebJobsFeatureFlags" for a Premium Function App.

**Comment by philliphoff** [comment]
Closing as deployment is now successful and there's a separate issue to automate the setting.
