### ISSUE TITLE
Not able to generate Linux Function App for Javascript/Node

### ISSUE THREAD

**Issue by jihu** [microsoft/vscode-azurefunctions#3313]
Hi,

This extension has worked great when helping us to setup Azure Functions in Azure. But when browsing the Azure Function App in the portal, I notice that the Operating System is Windows. 

According to the evaluation on the page below, cold starts for Javascript on Windows is several seconds longer than on Linux. So, we want to use Linux. But I can't find a way to make this extension do that.

https://mikhail.io/serverless/coldstarts/azure/

**Comment by nturinski** [comment]
Hi @jihu

Previously, the preferred OS for Node was Linux, but that behavior has changed. I'm not really sure why, but because it did, you'll have to use the advanced create to pick your operating system.

You can find it by either right-clicking the `Functions` tree item:
![image](https://user-images.githubusercontent.com/5290572/189237173-2638f3a7-100f-4802-ba20-403290ba1111.png)
 
Or by using the command palette (F1):
![image](https://user-images.githubusercontent.com/5290572/189237036-82924c73-931d-4702-b992-b91dcf4ac382.png)

Please let me know if that resolves your issue.
