### ISSUE TITLE
Event Grid local development experience improvements 

### ISSUE THREAD

**Issue by shreyabatra4** [microsoft/vscode-azurefunctions#3334]

**Comment by nturinski** [comment]
Could you please give us a little more information about what type local development improvements are expected? Is there some sort of design documentation that you could point us to?

**Comment by shreyabatra4** [comment]
@nturinski [Here](https://microsoft.sharepoint.com/:p:/t/EventGrid/EYytHRJsIXpKgij6xMqFlDgBU3n0ZI56hxuLIrhT6CbUzQ?e=7ajQLE) is the proposed design, please let me know if we can set up a call to discuss further

**Comment by jinglouMSFT** [comment]
@shreyabatra4 Where would you prioritize this ask against other asks from Functions?  For example, node.js programming model? Event Grid extension hasn't picked up its usage number since its inception.  Do you have any telemetry data from the service side?  Before we put investment in this, what's your success goal look like?  Thanks.
