### ISSUE TITLE
Having multiple create buttons is confusing

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurefunctions#3350]
When a customer has both Functions and SWA, it's confusing to see this:

<img width="509" alt="Screen Shot 2022-09-21 at 9 06 09 AM" src="https://user-images.githubusercontent.com/1186948/191582968-d6abee11-de4d-4618-bda2-c99209151f89.png">

I know that the commands are contributed independently, but what's possible to simplify how this is exposed?

**Comment by pamelafox** [comment]
Hm, it's more clear from the command menu as it's prefixed with the extension:

<img width="862" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/297042/191583948-ed8a9a7f-d03b-4234-896b-c72cdf41aa69.png">

<img width="712" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/297042/191583954-2c77e1df-edcd-4a1c-958f-2a4a5434b4cc.png">

but I imagine that would be quite wordy for the dropdown, might get truncated?

I have to admit, I'm now confused (as a user) as to why Static Web Apps need to create HTTP functions, but that's because I haven't explored SWAs at all. I might have a better suggestion when I learn more about SWAs. 

cc @kjaymiller (who took those screenshots)

**Comment by kjaymiller** [comment]
You can create a static web app from an azure function. I haven't tried this to see the difference but to my knowledge there are some javascript frameworks that can deploy a static site with a command. My assumption would be that this is to support that workflow.

**Comment by alexweininger** [comment]
We've been brainstorming solutions to this issue over on https://github.com/microsoft/vscode-azureresourcegroups/issues/316, feel free to chime in.

<img src="https://media4.giphy.com/media/VbEuHLBUPQm55MyqJg/giphy.gif"/>

**Comment by nturinski** [comment]
Temporarily, we can change the labels to be more explicit about which project it is adding to.
