### ISSUE TITLE
Error when trying to Create Function on Azure: OperationalInsights

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-azurefunctions#3352]
I am trying to follow the tutorial steps here:
https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python#publish-the-project-to-azure

However, each time I do it, I get this error:
<img width="537" alt="Screen Shot 2022-09-22 at 10 10 56 AM" src="https://user-images.githubusercontent.com/297042/191814735-5616dba8-024d-4772-b364-14baea1eb76b.png">

I followed the link to the page about errors, but this particular error isn't listed there, and I'm not sure how to resolve the lack of access to OperationalInsights, since I'm not quite sure what those are.

I also notice that my portal has successfully created application service plans each time I run through the process (so I assume the error happens after the creation of those plans):
<img width="856" alt="Screen Shot 2022-09-22 at 10 34 22 AM" src="https://user-images.githubusercontent.com/297042/191814734-72337d6c-f970-42e7-af5c-59a134297237.png">

**Comment by nturinski** [comment]
@pamelafox Thanks for bringing this to our attention. This is happening because the namespace `Microsoft.OperationalInsights` needs to be registered as a provider available to your subscription.

We usually do this for users automatically here: https://github.com/microsoft/vscode-azurefunctions/blob/main/src/utils/azure.ts#L69-L78

We recently started creating Log Analytics workspaces for users in the creation process, but we didn't realize that this has a different namespace that we should have registered.

The easiest workaround to this is to [create a Log Analytics workspace in the Azure Portal](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/quick-create-workspace?tabs=azure-portal).

**Comment by pamelafox** [comment]
I was also able to workaround it by registering the provider with AZ CLI from command line:

```
az provider register --namespace Microsoft.OperationalInsights
```

Thanks for working on a fix!
