### ISSUE TITLE
Node model v4: AppSetting validation

### ISSUE THREAD

**Issue by horihiro** [microsoft/vscode-azurefunctions#3559]
It might be good for developers to validate if AppSetting `AzureWebJobsFeatureFlags` has `EnableWorkerIndexing` when deploying functions of Node model v4.

**Comment by ejizba** [comment]
Hi @horihiro the app setting will no longer be necessary in the near future. This was fixed in the functions host in https://github.com/Azure/azure-functions-host/pull/8864 and will be rolling out soon (for sure before we announce public preview). With that in mind, I don't think it's worth implementing validation in VS Code

**Comment by ejizba** [comment]
Unfortunately the host team had to revert the flag change because they ran into some issues https://github.com/Azure/azure-functions-host/pull/9163. I don't know when they will be able to revert the revert, so might be worth considering this enhancement. Fyi @nturinski
