### ISSUE TITLE
Sort locations in location step alphabetically

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurefunctions#3576]
Is there a reason the locations aren't sorted in this list? I feel like they should be.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/12476526/219820877-9f631cff-90de-4c9f-a02f-72d9fc42d1d8.png">

I know the code is in the tools repo, but the UX is here.

**Comment by nturinski** [comment]
Yeah, not sure. It's sorted in the portal, but it also defaults to East US. I don't think we could do both.

**Comment by ejizba** [comment]
We used to sort alphabetically (https://github.com/microsoft/vscode-azuretools/pull/282), but got rid of it in favor of the order returned in the api (https://github.com/microsoft/vscode-azuretools/pull/894).

I don't remember if someone told me to do that or not, but I thought the order returned in the api was somewhat smart based on your subscription and other mysterious reasons like capacity idk. Otherwise they'd end up with everyone putting their stuff in Australia

**Comment by alexweininger** [comment]
> Yeah, not sure. It's sorted in the portal, but it also defaults to East US. I don't think we could do both.

Ahh, that makes sense.

> We used to sort alphabetically ([microsoft/vscode-azuretools#282](https://github.com/microsoft/vscode-azuretools/pull/282)), but got rid of it in favor of the order returned in the api ([microsoft/vscode-azuretools#894](https://github.com/microsoft/vscode-azuretools/pull/894)).

Eric coming in with the history lesson 🚀 

> I don't remember if someone told me to do that or not, but I thought the order returned in the api was somewhat smart based on your subscription and other mysterious reasons like capacity idk. Otherwise they'd end up with everyone putting their stuff in Australia

Interesting 🤔
