### ISSUE TITLE
Error deploying Azure Function (Python) Deployment 'latest' not found.

### ISSUE THREAD

**Issue by wouter-in2facts** [microsoft/vscode-azurefunctions#3691]
When trying to deploy a recently successfully deployed (Python) Azure Function, I am receiving the following error

`Error: Deployment 'latest' not found.`

> 9:12:34 AM my-function-name: Starting deployment...
> 9:12:34 AM my-function-name: Creating zip package...
> 9:12:41 AM my-function-name: Zip package size: 31.5 MB
> 9:12:41 AM my-function-name: Fetching changes.
> 9:13:44 AM: Error: Deployment 'latest' not found.

Extension version v1.10.7

**Comment by wouter-in2facts** [comment]
It seems to  give this error message at different stages in the deployment process every time

**Comment by wouter-in2facts** [comment]
and then trying again shortly after that

10:15:55 AM my-function-name: Starting deployment...
10:15:55 AM my-function-name: Creating zip package...
10:16:02 AM my-function-name: Zip package size: 31.5 MB
10:16:06 AM: Error: Deployment 'latest' not found.

**Comment by wouter-in2facts** [comment]
Note: it turns out the Azure Function must be enabled for the deployment to work

**Comment by yuanweilei** [comment]
Hi, @wouter-in2facts 
Can we reopen this issue? 

I noticed that sometimes the same error "Error: Deployment 'latest' not found." occurred even the Functions App is running. 
The error message is the response of "api/deployments/latest".
https://github.com/projectkudu/kudu/wiki/REST-API#deployment

VS Code uses KuduLite to deploy and it seems that it is polling "api/deployments/latest" during the deployement. Since there are no persistent logs in Linux Consumption plan, the polling fails sometimes and get 404 "Error: Deployment 'latest' not found."

I think it is better to update the VS Code deployment feature, for example, polling "api/deployments/latest" and check the status is 4 which means "success".
