### ISSUE TITLE
An error occurs when debugging a C# project

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3748]
**OS:** All
**Build Version:** 20230711.5
**Regression:** Preview Release

**Repro Steps:**

1. Create a C# project with "HttpTrigger" template.
2. Set a breakpoint.
3. F5
4. Check whether succeeds to debug the project.

**Expect:**
Succeed to debug the project.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/107091828/45e6d3af-d426-41e7-ab54-944bea43f5ad)

**More Info:**
This issue also reproduces when debugging C# project with "Durable Function orchestrator" function.

**Comment by nturinski** [comment]
I can reproduce this on our main branch and confirmed that this fixes it.

Just to clarify, the project still debugs, but never attaches. So the func host is running and the trigger will be execute, but your debugger never attaches and therefore cannot hit breakpoints.

However, listing local triggers isn't fixed due to the same error. I wonder if there's somewhere lower level where we can apply this setting?
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/d6372e26-09f2-43f9-a203-07bead701326)

**Comment by nturinski** [comment]
Turns out we make this request separately for local tree items, so I'd just add it to `'LocalFunctionsTreeItem.getChildrenForHostedProjects` as well. Or maybe we could extract it out as a util function 🤷
