### ISSUE TITLE
azure functions Could not load file or assembly System.IdentityModel.Tokens.Jwt.dll The system cannot find the file specified.

### ISSUE THREAD

**Issue by longtimedeveloper** [microsoft/vscode-azurefunctions#3829]
When I run my Azure Functions project in **vscode**, the `System.IdentityModel.Tokens.Jwt.dll` file is being removed from the `\PROJECTNAME\bin\Debug\net6.0\bin` folder.

The only way I can find to fix this overly aggressive cleaning of the folder is to use the  **_FunctionsSkipCleanOutput** setting.  Of course this also leave so many other DLLs in the folder as well.

    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>

Yes, I am creating objects from this DLL in my code.  

Example:  `var handler = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler();`

But for some reason, the tooling is not recognizing that my code is really using the DLL and that it must be included and not removed.

**Can you please fix this?** 

Thank you!

**Comment by nturinski** [comment]
Hi @longtimedeveloper

Sorry for the issue, but I don't think the extension tools can really do anything about this.  If you check your `task.json`, we are running a `dotnet clean` before a `build` or `publish` task.

Since we're just running `dotnet` CLI command, I don't think we have control over exactly what gets cleaned and what doesn't.  There may be a way to set up exceptions and pass those files in as arguments?

You may also have some better luck asking over at the [C# Extension](https://github.com/dotnet/vscode-csharp/issues) since they are .NET subject matter experts.  They may have a setting in their extension for this already.

**Comment by longtimedeveloper** [comment]
@nturinski thank you for the response.  I'll follow your recommendation and log the issues in [C# Extension](https://github.com/dotnet/vscode-csharp/issues).  Thank you.
