### ISSUE TITLE
Error failed to get templates

### ISSUE THREAD

**Issue by garyckhsu** [Microsoft/vscode-azurefunctions#398]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.createFunction
Error type: Error
Error Message: There was an error in retrieving the templates.  Recheck your internet connection and try again.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @garyckhsu,

I'm sorry that you weren't able to create any functions through the extension.  Do you mind giving me a few more details so that I can try to help you resolve your issue?

1. What language is the template that you are trying to create?
1. Under what runtime are you trying to create a function in?
1 What type of trigger are you trying to create? (HttpTrigger, BlobTrigger, etc.)

Thank you for your assistance in resolving this and sorry again for the trouble.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information

**Comment by deepak113016** [comment]
Hi @nturinski 
      I am also facing same problem.
     Below are the some details that you have asked in earlier post
  1. JavaScript
  2.v1
  3.HTTPTrigger

Thanks

**Comment by nturinski** [comment]
Hi @deepak113016,

Thanks for answering my questions and sorry for the delay in response.  Has this been resolved for you?  

It seems like there is an issue downloading the zip file that contains the template (~1MB).  Do you have any restrictions in your internet connection?

**Comment by EricJizbaMSFT** [comment]
Will be fixed as a part of #462
