### ISSUE TITLE
Java project will be initialized as C# project

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#407]
## Repro steps:

1. Given a default Java Functions project, run `mvn clean package`
2. An `extensions.csproj` will be generated at the base path, this file stores the package and version information of the function extensions
3. init the project in VS Code Azure Functions extensions

## Expected behavior:
The project will be initialized as Java project

## Actual behavior:
The project is initialized as C# project

## Root Cause:
Here https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/commands/createNewProject/detectProjectLanguage.ts#L22

We detect the project as Java project only when it has `pom.xml` at base path and not contains any `*.csproj`. @EricJizbaMSFT is it possible that we remove the `!isCSharp` condition here?

**Comment by EricJizbaMSFT** [comment]
Feels like we should prompt the user to select the language if there's a csproj file and pom.xml, rather than assume it's Java. Aka rather than remove `!isCSharp` from line 22, add `!isJava` to [line 24](https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/commands/createNewProject/detectProjectLanguage.ts#L24)

**Comment by jdneo** [comment]
That sounds good
