### ISSUE TITLE
There are no "Start Streaming Logs" and "Stop Streaming Logs" actions for a function app with Flex Consumption (Preview) hosting plan

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#4087]
**OS:** All
**Build Version:** v1.14.2-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create a function app with Flex Consumption (Preview) hosting plan and East Asia location.
2. Right click the above function app to open its context menu.
3. Check whether there are "Start Streaming Logs" and "Stop Streaming Logs" actions.

**Expect:**
There are "Start Streaming Logs" and "Stop Streaming Logs" actions.

**Actual:**
There are no "Start Streaming Logs" and "Stop Streaming Logs" actions.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/025f5142-289e-4d9e-8dcc-28919ab06533)

**More Info:**
There are "Start Streaming Logs" and "Stop Streaming Logs" actions in function context menu after deploying a function project to a function app with Flex Consumption (Preview) hosting plan.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/98787e2f-b04f-4a29-8ef9-949434b426c7)

**Comment by nturinski** [comment]
The function context menu takes the user to a different log streaming than the function app one.

The function live streaming looks like this:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/997b1655-1254-443c-8767-9573713aa87e)

It is specific to the function trigger itself.

Currently, I don't think that the log streaming for the function app is working correctly which is why it was removed from the context menu for flex apps.
