### ISSUE TITLE
Getting warning message "Matches multiple schemas when only one must validate." in host.json file

### ISSUE THREAD

**Issue by RyanHill-MSFT** [microsoft/vscode-azurefunctions#4093]
See MicrosoftDocs/azure-docs#121718, the VS Code editor throws a warning message for multiple schema matches on host.json.

<img width="665" alt="323232982-df354fbf-ebb8-4d3f-a036-c0ba7799e9f7" src="https://github.com/microsoft/vscode-azurefunctions/assets/47189704/a4a96a9f-37db-44ed-86ef-5ba217650d22">

**Comment by nturinski** [comment]
Hi @RyanHill-MSFT,

This warning is coming up because the Azure Logic Apps extension also contributes a host.json schema that is identical to ours. For some reason, VS Code will only validate one schema per file and is throwing this warning.

To get rid of the warning, I recommend uninstalling the Azure Logic Apps extension if you don't need it. Also please file this issue on https://github.com/microsoft/vscode/issues since we can't control this warning.
