### ISSUE TITLE
.ignore functionality

### ISSUE THREAD

**Issue by erezak** [Microsoft/vscode-azurefunctions#418]
To shorten deployment time, I'd like to be able to mark node_modules folder in a .ignore file, and later install the npm dependencies using the Kudu tools.

Is there such a functionality - similar to .gitignore, .npmignore, etc.?

**Comment by erezak** [comment]
Probably related to https://github.com/Azure/azure-functions-core-tools/issues/341

**Comment by fiveisprime** [comment]
Should we honor the `.funcignore` file as well or use a workspace setting (how we handle this in the other extensions)?

I'm thinking that if there's already a common practice, we adopt that.

**Comment by erezak** [comment]
I think the .funcignore option.

**Comment by nturinski** [comment]
There are workspace settings that you can set to ignore the node_modules for now.

`"azureFunctions.zipGlobPattern": {`
`                        "scope": "resource",`
`                        "type": "string",`
`                        "default": "**/*",`
`                        "description": "Defines which files in the workspace to deploy. This applies to Zip deploy only, has no effect on other deployment methods."`
`                    }`

`                    "azureFunctions.zipIgnorePattern": {`
`                        "scope": "resource",`
`                        "type": [`
 `                           "string",`
`                            "array"`
 `                       ],`
`                        "default": "",`
 `                       "description": "Defines which files in the workspace to ignore for Zip deploy. This applies to Zip deploy only, has no effect on other deployment methods."`
`                    },`

But I agree with @fiveisprime that we should adopt a common practice rather than leveraging workspace settings.
