### ISSUE TITLE
Completely broken? No functions under 'Local Project', and deploying says successful but isn't.

### ISSUE THREAD

**Issue by maxiedaniels** [microsoft/vscode-azurefunctions#4207]
I just installed this extension, and tried to load up my existing function project - doesn't work. It shows 'Local Project' with the correct path, but in 'Functions', it shows 'Start debugging to update this list...'. Obviously I tried debugging, no luck.

Then i tried to create a new function, same issue!

Even more importantly - with the function_app.py open, I right clicked the function app instance in my Azure subscription (in the Resources menu) and did deploy to function app. Confirmed, it takes a while, then it says it was successful. But when I open the function in Azure portal, it shows no functions.

Is this extension totally broken?

**Comment by nturinski** [comment]
Hi @maxiedaniels

Sorry that you're having issues with the extension. It shouldn't be completely busted. Let me ask a couple of questions to see if I can't help debug some of these issues.

> I just installed this extension, and tried to load up my existing function project - doesn't work. It shows 'Local Project' with the correct path, but in 'Functions', it shows 'Start debugging to update this list...'. Obviously I tried debugging, no luck.

After debugging, could you try refreshing that Workspace pane?

![image](https://github.com/microsoft/vscode-azurefunctions/assets/5290572/948e8229-fc7b-41ce-8740-f6f781f574a8)

As far the the deployment, I'm not sure why it wouldn't be showing up. Sometimes the deployment can appear successful, but there are some runtime issues that the extension don't catch. For example, if you have a Python 3.9 project, but you deploy to a Python 3.8 function app.

Could you give me more information on how you created the function app and function project?  Would it be possible to try creating a new project through the extension? Sometimes the extension doesn't work well with existing projects since the configurations can all vary slightly.

**Comment by nturinski** [comment]
Hi @maxiedaniels 

Any update on this issue? Did any of my suggestions work?

**Comment by nturinski** [comment]
It's all good, I understand that we all have those sort of days 😊 

Glad that everything got resolved!
