### ISSUE TITLE
Default Branch Name is always master when creating new project

### ISSUE THREAD

**Issue by robinhalabicki** [microsoft/vscode-azurefunctions#4262]
VS Code Version: 1.93
OS Version: Windoes_NT x64 10.0.22631
Steps to Reproduce:

Command Palatte
Azure Functions: Create New function
(walk through)
After the project is created the default branch is master even though the VS Code setting for Git: Default Branch Name is "main"

**Comment by nturinski** [comment]
Hi @robinhalabicki

I don't think that the Functions extension is the one initializing the git repository. How are you initializing it?

**Comment by robinhalabicki** [comment]
I am not, I literally create the function using the Palette.   Then the git extension shows its default branch is master, even though the setting is main in the settings

**Comment by nturinski** [comment]
Could you tell me your git version?

`git -v`

**Comment by robinhalabicki** [comment]
git version 2.45.1.windows.1

**Comment by nturinski** [comment]
Weird. Maybe the folder that you're in has a parent folder that has a git repository with the master branch? I really have no idea why it's doing that, but it should be unrelated to the Functions extension since we don't initialize the repository for the user.

**Comment by robinhalabicki** [comment]
I wondered that too.   

But, 
if I open Git Desktop and create a new folder for new local repo, it defaults to main
if I open VS Code, open folder, create new folder, click on the source control, click initialize, it defaults to main 
if I open VS Code, open folder, create new folder, CTRL+SHIFT+P, Create new function, walk through, it defaults to 'master'

**Comment by nturinski** [comment]
My teammate fact-checked me thankfully. I forgot, we _do_ initialize a repo if you don't have one on create: https://github.com/microsoft/vscode-azurefunctions/blob/010c071035bb6a8e441741b3a9912497abbcc4c3/src/commands/createNewProject/ProjectCreateStep/ProjectCreateStepBase.ts#L28

Our current theory is that because we're running it through a child process, that it's using your git config settings and not the VS Code settings when initializing the repo.

You can try changing that like so
`git config --global init.defaultBranch main`

We should switch to using the VS Code Git API to do this though, but this should hopefully suffice as a workaround in the meantime.

**Comment by robinhalabicki** [comment]
HAZZAH!   Bingo, worked, thank you.

**Comment by robinhalabicki** [comment]
Close this, possibly add a fix/feature to use the VS Code setting for the Function Extension
