### ISSUE TITLE
Add support for C# scripts

### ISSUE THREAD

**Issue by carlowahlstedt** [Microsoft/vscode-azurefunctions#43]
Was just testing the extension and it looks like when adding a new function it add for js only. Would be good to see it also support C#.

**Comment by EricJizbaMSFT** [comment]
@carlowahlstedt we plan to add support for C# class libraries ('.cs' files - basically mirroring the experience of VS today).

However, we could additionally add support for C# script files ('.csx' files - mirroring the experience in the portal). Are you interested in C# script files - or just C# class libraries?

**Comment by carlowahlstedt** [comment]
Script files (.csx) is what I was using and what I would be more interested in.

Thanks!

**Comment by EricJizbaMSFT** [comment]
Scoping this issue to add support for C# _scripts_ since that is what @carlowahlstedt is more interested in. The C# class library issues can be tracked here: #162 #160 

For the sake of full disclosure, we chose to prioritize class libraries over C# scripts for the following reasons:
1. Per the Functions team, scripts have worse performance and are less versatile than class libraries
1. The functions cli does not support local debug for C# scripts. If you want that fixed, file an issue in [this repo](https://github.com/Azure/azure-functions-cli). (Once it's fixed, we should be able to leverage the [mono extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug) to debug in VS Code)
