### ISSUE TITLE
Error: Command "wmic process get CommandLine,Name,ProcessId /FORMAT:csv" failed with exit code "44210":

### ISSUE THREAD

**Issue by alexjamesbrown** [Microsoft/vscode-azurefunctions#437]
Repro steps:
Create a new function project
Add a c# function
(.net core)

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Command "wmic process get CommandLine,Name,ProcessId /FORMAT:csv" failed with exit code "44210":
Invalid XSL format (or) file name.

Version: 0.9.1
OS: win32

-----

Using "C#" as the project language...
Using "beta" as the project runtime...
Using "Verified" as the project templateFilter...
Writing project debug configuration...
Writing project settings...
Writing extension recommendations...
Verifying ".vscode" is not listed in gitignore...
Finished initializing for use with VS Code.
Running command: "dotnet new HttpTrigger --name="HttpTrigger" --namespace="MyNamespace" --AccessRights="anonymous""...
The template "HttpTrigger" was created successfully.

Processing post-creation actions...
Description: Opens the function class file in the editor
Manual instructions: 

Finished running command: "dotnet new HttpTrigger --name="HttpTrigger" --namespace="MyNamespace" --AccessRights="anonymous"".
Error: Command "wmic process get CommandLine,Name,ProcessId /FORMAT:csv" failed with exit code "44210":
Invalid XSL format (or) file name.

**Comment by EricJizbaMSFT** [comment]
@alexjamesbrown are you by chance on Windows 7? I found a known-bug with wmic in Windows 7. Please take a looks and see if this helps:
https://stackoverflow.com/questions/9673057/wmic-error-invalid-xsl-format-in-windows7

https://social.msdn.microsoft.com/Forums/vstudio/en-US/a9beeed3-99f0-4627-ba1e-aa0161fa58c9/wmic-invalid-xsl-format-or-file-name?forum=windowsgeneraldevelopmentissues

**Comment by alexjamesbrown** [comment]
@EricJizbaMSFT yeah, windows 7 -
UK machine, so can't change the lang really...
guess I'm stuck?

**Comment by EricJizbaMSFT** [comment]
The first stackoverflow I linked to listed this as a possible workaround:

> Copy or move the C:\Windows\system32\wbem\en-US\*.xsl files up into the C:\Windows\system32\wbem\ folder.

Hopefully that would fix it.

**Comment by rohancragg** [comment]
I also get this on a Windows 10 (1803) machine in the UK :-(

**Comment by EricJizbaMSFT** [comment]
Hey all - sorry for the delay, but I've completely refactored this and I'm hoping to get your help testing if you have time (and if you never got this working for yourself).

Please install the following vsix leveraging the "Install from VSIX" command in VS Code's command palette:
![screen shot 2018-09-04 at 10 28 44 am](https://user-images.githubusercontent.com/11282622/45047234-53c16400-b02d-11e8-93d6-514f3ee3f9ad.png)

VSIX:
https://azcode.blob.core.windows.net/vscode-azurefunctions/ej/proc/1627/vscode-azurefunctions-0.10.1-alpha.vsix

Otherwise just follow your normal debugging routine for C# projects and let me know if it works.
