### ISSUE TITLE
Support Linux Consumption apps

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#482]
This is the run-from-zip scenario where there will be no Kudu.

Any apps that are configured for Linux consumption should be published using run-from-zip, it's possible to detect the configuration.

The ARM app should look like 
 
```js
{
  ...
  "kind": "functionapp,linux",
  ...
  "properties": {
    ...
    "sku": "Dynamic",
    ...
  }
}
```
 
And the conditions to check for are:
 
```js
app.kind.toLowerCase().indexOf('functionapp') !== -1 &&
  app.kind.toLowerCase().indexOf('linux') !== -1 &&
  app.properties.sku.toLowerCase() === 'dynamic'
```

**Comment by EricJizbaMSFT** [comment]
Only thing left on this is to support this when creating function apps

**Comment by EricJizbaMSFT** [comment]
Create will be tracked in this issue: https://github.com/Microsoft/vscode-azurefunctions/issues/587
Log stream will be tracked here: https://github.com/Microsoft/vscode-azurefunctions/issues/589

The other work was fixed in https://github.com/Microsoft/vscode-azurefunctions/pull/574 and https://github.com/Microsoft/vscode-azurefunctions/pull/577
