### ISSUE TITLE
Support more Java trigger templates

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#486]
Start from Maven Azure Functions plugin: `1.0.0-beta-3`, users can add more Java trigger templates, including:
- EventGrid
- EventHub
- Cosmos DB
- Service Bus Queue
- Service Bus Topic

For short-term plan, check the pom and get the version of the plugin to determine which templates are available.
For long-term plan, we will check the possibility to add Java templates into the tooling feed and consume the templates directly from the feed.

@EricJizbaMSFT What do you think?

**Comment by EricJizbaMSFT** [comment]
I would really prefer if we came up with a long-term solution rather than another workaround. If we had fixed https://github.com/Microsoft/vscode-azurefunctions/issues/84 anytime between now and _last November_, users would've automatically gotten all of these templates already. I think this is a great catalyst to get that work done.

Adding the templates to some sort of feed is an option. However, would it be possible for maven or the plugin itself to output information about the templates?

**Comment by jdneo** [comment]
@pragnagopa @soninaren

Eric proposed another solution that the templates & metadata still stored in Maven plugin, and the plugin will have another command to output the templates information itself. (@EricJizbaMSFT Correct me if I misunderstood). This could easily solve the version control problem and looks easier to achieve than adding templates to tooling feed.

Please let me know your thoughts. Personally I vote for this solution.

**Comment by soninaren** [comment]
@jdneo 
I agree with Eric proposed solution, We should add a list-templates command / functionality to the maven plugin, it would provide templates and related metadata as a json. We should also with the maven plugin version to the cli-feed, the VS Code can check the users machine to verify if the right version of maven plugin is installed, and can warn users if it does not match. I will add the plugin version to the cli-feed as soon as the plugin update is ready.

**Comment by jdneo** [comment]
PR for Maven plugin: https://github.com/Microsoft/azure-maven-plugins/pull/310

**Comment by jdneo** [comment]
@EricJizbaMSFT PR updated, please take a look when you have time :)
