### ISSUE TITLE
Support using extension behind proxy server

### ISSUE THREAD

**Issue by rricart** [Microsoft/vscode-azurefunctions#493]
Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: SELF_SIGNED_CERT_IN_CHAIN
Error Message: self signed certificate in certificate chain

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@rricart can you give a little more info:
1. What type of project were you deploying?
1. Does this happen consistently?
1. Is there anything unique about internet connection? Proxies or vpns or anything like that

**Comment by ciwchris** [comment]
I consistently get this when trying to deploy an Azure Function. I am in a network which uses a proxy server which man in the the middles all traffic and uses a self sign certificate internally. Is there a way to supply a new certificate chain for this VS Code extension to use so that it recognizes the self signed certificate?

**Comment by EricJizbaMSFT** [comment]
@ciwchris I believe we would have to add support for the following settings to support proxies:
`http.proxy`
`http.proxyStrictSSL`
`http.proxyAuthorization`

You can try these instructions (if you haven't already), but I don't think it works for extensions: https://code.visualstudio.com/docs/setup/network#_proxy-server-support due to this issue: https://github.com/Microsoft/vscode/issues/12588

Let me know if that works, but I'll put this as a feature on our backlog because I don't think it will.

**Comment by ciwchris** [comment]
Thanks. I experimented with a few different settings without success.

**Comment by EricJizbaMSFT** [comment]
Extension support for proxies has been recently added in VS Code insiders. You're welcome to try it out. See here for more info: https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-441998815

I'll leave this open for tracking

**Comment by EricJizbaMSFT** [comment]
Closing this as VS Code released proxy support for extensions:
https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions
