### ISSUE TITLE
Best way to establish output bindings? Is best practice to edit the /bin folder? 

### ISSUE THREAD

**Issue by timmyreilly** [Microsoft/vscode-azurefunctions#529]
I want to add an output binding to Cosmos DB for local testing. What's the best way to add the configuration for output bindings? Do I just edit the JSON file in the /bin directory? Or is there a file that I'm not seeing that has configuration?

**Comment by timmyreilly** [comment]
Cool, so the binding should go in the function. Do you think you could qualify why I should use output bindings for CosmosDB instead of just speaking directly to the Cosmos Library? eg: Microsoft.Azure.Documents.Client

**Comment by EricJizbaMSFT** [comment]
@jeffhollan thoughts on @timmyreilly's question?

**Comment by EricJizbaMSFT** [comment]
Closing this due to lack of response. @timmyreilly if you're still looking for an answer I suggest you follow one of the guidelines from here: https://github.com/Azure/Azure-Functions#questions--help

We also plan to add better support for bindings in our extension. That's being tracked here: https://github.com/Microsoft/vscode-azurefunctions/issues/775
