### ISSUE TITLE
VS Code Azure Functions extensions warns to update to Core Tools 2.0.1-beta.37 even though the Ubuntu 18.04 PPA has no such version

### ISSUE THREAD

**Issue by polarapfel** [Microsoft/vscode-azurefunctions#548]
The Azure Functions extension for VS Code warns:

> Update your Azure Functions Core Tools (2.0.1-beta.35) to the latest (2.0.1-beta.37) for the best experience. v2 is in preview and may have breaking changes (which are automatically applied to Azure).

However, there is no such version in the Ubuntu 18.04 PPA (yet), the latest version published is still 2.0.1-beta.35.

**Comment by EricJizbaMSFT** [comment]
We check npm to see what the latest version is since npm is the only install method that's available on all OS's. You're welcome to install with npm if you want to be on the latest or turn the warning off with "Don't warn again".

The only fix I can see is to check every different install method and base the warning on that, but I'm not sure that's worth investing in. Ideally the functions cli releases every option with a few days of each other anyway

You're welcome to contribute a fix. Otherwise any objection to me closing this as won't-fix?
