### ISSUE TITLE
Error when publishing a Python app on Linux Consumption

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#625]
Environment: 
	• MacOS
	• Azure Functions extension 0.11.0 with azureFunctions.enablePython==true
	• Core Tools 2.0.2.0

Repro steps:

1. Create new Python project worked great
2. Create new HTTP triggered function worked great
3. F5 experience was perfect!
4. Publishing to a Linux consumption app in Azure failed terribly

     - On publish, I picked '+Create new app' and gave it the relevant details including app name, resource group name, storage account name, region ,etc. 
     - The app was created but portal threw the following errors. Doesn't look like the functions were indexed. 

![image](https://user-images.githubusercontent.com/8435148/45852461-dff1ad80-bcf4-11e8-8137-53c1e01bee23.png)

It seems the the publish is setting the following app settings:

- WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
- WEBSITE_CONTENTSHARE

These are not required for consumption and cause an error in the publishing experience.

**Comment by EricJizbaMSFT** [comment]
I see those app settings when I create a function app from the portal. Plus they're listed here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#websitecontentazurefileconnectionstring Are you sure that's causing the problem?

Can you create a linux consumption function app in the portal and try to list the functions in the portal? It doesn't work for me, which makes me think the issue is not with VS Code
<img width="224" alt="screen shot 2018-09-20 at 4 56 24 pm" src="https://user-images.githubusercontent.com/11282622/45852733-2267ba00-bcf6-11e8-803a-59bc046e0c46.png">

I've always seen that error (aka deploy has never worked for me) and I need someone on the functions team to help figure out what's wrong.

**Comment by davidebbo** [comment]
I wonder if it's related to #630, where bad app settings break the runtime.

**Comment by EricJizbaMSFT** [comment]
Voila! The mystery is solved! I removed those settings and it worked. I'll get a fix in - but someone needs to fix this in the portal, too.

Should we remove those for windows plans as well as linux?

**Comment by davidebbo** [comment]
@EricJizbaMSFT so it's a little complicated (and you're probably going to hate us (more))...

There are two scenarios for the Linux case:

1. For an app meant for Portal editing, it's expected to have those two `WEBSITE_CONTENT...` settings
1. For an app published from client, they must not be there, and instead it uses `WEBSITE_RUN_FROM_ZIP`

The catch is that when creating an App via Portal, it always adds the two `WEBSITE_CONTENT...` settings, even if the user's intention is to publish from client. To work around this, what @ahmelsayed did in `func publish` is that he detects that those are set, and refuses to publish, unless user specifies `--force`. And with `--force`. he yanks them and adds `WEBSITE_RUN_FROM_ZIP`.

But for WIndows you actually do need to keep those settings in addition to adding `WEBSITE_RUN_FROM_ZIP`.

Clearly, we need to clean this mess on our side, but as it stands, that's the situation.
