### ISSUE TITLE
VS Code keeps prompting to install pylint

### ISSUE THREAD

**Issue by davidebbo** [Microsoft/vscode-azurefunctions#631]
![image](https://user-images.githubusercontent.com/556238/45853156-72478080-bcf8-11e8-82fd-a6d199f28f60.png)

I've several time told it to install it, but it seems to keep coming up.

**Comment by qubitron** [comment]
@EricJizbaMSFT we shouldn't be installing pylint by default, we want to move away from pylint in favor of the language server in future releases. 

The bug here is that the pylint prompt doesn't go away after David clicks install, which should is an issue that should be filed & fixed by the VS Code extension

**Comment by EricJizbaMSFT** [comment]
> The bug here is that the pylint prompt doesn't go away after David clicks install

Not quite true since "Install" _was_ working. It was installing inside the virtual environment for the project. So the next time he created a project he got a clean virtual environment that didn't have pylint. Thus "I've several time told it to install it" was really only once per project
