### ISSUE TITLE
Add Event Grid/Event Hub triggers to 'Verified' category

### ISSUE THREAD

**Issue by priyaananthasankar** [Microsoft/vscode-azurefunctions#690]
Created a new function within VS Code (Python on Functions) and saw these options:
![image](https://user-images.githubusercontent.com/10415876/46437767-fa725080-c710-11e8-85db-4a83d5ffdfb5.png)

But the func core tools outside VS Code shows me Event Grid/Event Hub options as well:

![image](https://user-images.githubusercontent.com/10415876/46437879-40c7af80-c711-11e8-9726-8ec844c9ce97.png)

**Comment by EricJizbaMSFT** [comment]
You can change the 'template filter' at the bottom to 'All:
![screen shot 2018-10-03 at 1 57 44 pm](https://user-images.githubusercontent.com/11282622/46439081-702beb80-c714-11e8-9150-d35330753194.png)

And you should see more templates:
![screen shot 2018-10-03 at 1 57 57 pm](https://user-images.githubusercontent.com/11282622/46439068-67d3b080-c714-11e8-91e9-e71471699512.png)

We dynamically retrieve the templates and the 'verified' category is just a way for us to ensure any new templates actually work before being displayed to all users. For example - the Cosmos DB trigger has full support and will list out your Cosmos DB accounts as a part of creation:
![screen shot 2018-10-03 at 2 01 37 pm](https://user-images.githubusercontent.com/11282622/46439231-e6c8e900-c714-11e8-88bd-bdede41584f5.png)

The Event Hub and Event Grid triggers don't have that support yet and will make you get the connection string manually (but otherwise will probably work):
![screen shot 2018-10-03 at 2 02 41 pm](https://user-images.githubusercontent.com/11282622/46439271-019b5d80-c715-11e8-9de7-efd913e8c88f.png)

**Comment by priyaananthasankar** [comment]
Oops. Missed that. Closing the issue. Thanks!

**Comment by EricJizbaMSFT** [comment]
No problem. We can actually keep this open to add these to the 'Verified' category. I've already changed the title of the issue. Getting this feedback helps us prioritize which templates to add "full support" for (There's not a huge list under "All" for Python, but some other languages have a ton of templates)

**Comment by fiveisprime** [comment]
1. EventHub trigger
1. Event Grid 
1. Durable Functions (don’t think we have javascript in our templates repo yet)
1. IoT Hub

**Comment by EricJizbaMSFT** [comment]
Event Grid and Durable was added for all languages that support it. It's confusing to track _all_ templates in the same issue, so closing this and I've created separate issues for other types:

Event Hub: https://github.com/Microsoft/vscode-azurefunctions/issues/1035
IoT Hub: https://github.com/Microsoft/vscode-azurefunctions/issues/1036
