### ISSUE TITLE
Running a Java function app repeatedly on VS Code is not stable

### ISSUE THREAD

**Issue by nzthiago** [Microsoft/vscode-azurefunctions#721]
Running a Java function app repeatedly on VS Code is not stable:
•	There are many instances where the debugger fails to attach
•	VS code is unresponsive to "Start Without Debugging"
•	Function host constantly hangs and takes the 7071 port with it (might not be a Java-only issue)

@asavaritayal

**Comment by asavaritayal** [comment]
Pinging thread to see if there's an update here . /cc @EricJizbaMSFT @jdneo

**Comment by nzthiago** [comment]
Adding @daniel-rocha too - have you tried Functions with VS Code and Java recently? Checking if these issues with VS Code hanging are still manifesting

**Comment by jdneo** [comment]
Hi @nzthiago,

> There are many instances where the debugger fails to attach

I tried several times on my side, but not able to repro it.

> VS code is unresponsive to "Start Without Debugging"

I'll sync with the devs of the Java Debugger extension

> Function host constantly hangs and takes the 7071 port with it (might not be a Java-only issue)

Still not able to repro, is your function cli latest?

**Comment by jdneo** [comment]
Ok, after syncing with the dev, `Start Without Debugging` makes no sense here, because the request type here is `attach` instead of `launch`. So the user still can see the call stacks and able to hit the breakpoints.

**Comment by nzthiago** [comment]
We first ran into this in June so it could well be that the issues were fixed. Checking if @daniel-rocha or @brusMX can review (I think you raised this feedback from our OpenHack in London Bruno).

**Comment by nzthiago** [comment]
I disagree that `Start without Debugging` makes no sense; a lot of developers like to use that when they just want to try running what they're working on without the extra time it takes for the debugger to attach and hit breakpoints and etc. Sometimes I just want to kick off the func host and start the functions I'm working on without attaching and hitting start without debugging or Ctrl+F5 is easier/faster than going to the command line and running the commands manually.

Looks like the Start without Debugging was fixed with this for VS Code and Java in August? https://github.com/Microsoft/vscode-java-debug/issues/351

**Comment by EricJizbaMSFT** [comment]
@nzthiago the issue you linked to doesn't quite apply in this case. That is when you're launching a Java process directly, but in our case we're launching the Azure Functions runtime, which launches a Java process for us. If you look in your `.vscode/launch.json` you'll see the request is "attach" instead of "launch" because we only ever attach to the process created by the func cli. Without the 'func' cli intermediary, this would be super simple to fix.

I think this makes sense as a feature request, but it actually applies to all of our languages (not just java) and it would probably require some big changes just to get working. For those reasons, I've filed a separate issue here to track: https://github.com/Microsoft/vscode-azurefunctions/issues/1064 and hopefully this issue can just focus on the java-specific bullet points from above.

**Comment by jdneo** [comment]
@EricJizbaMSFT Thank you for clarifying. 👍 

Yes, let's focus on the Java-specific problems in this issue.

**Comment by nzthiago** [comment]
@EricJizbaMSFT @jdneo - agreed! Thanks for creating #1064 
Thank you for looking into this and trying to repo the other two parts - I will close this issue as you can't repro what our team was seeing last year, if I get any more data I'll open new entries and reference this. Thanks
