### ISSUE TITLE
Use the python version active in the current python extension

### ISSUE THREAD

**Issue by qubitron** [Microsoft/vscode-azurefunctions#753]
The functions extension should use the Python version selected using the interpreter selector specified by the user.

Per:
https://code.visualstudio.com/docs/python/environments

Use the python.pythonPath setting to get the python interpreter currently selected in the extension.

**Comment by EricJizbaMSFT** [comment]
We can definitely respect the "python.pythonPath" setting if it's at the "user" level.

However, it seems like that setting is usually created at the workspace level. That won't help us since we need to select the interpreter _before_ creating a python project (aka in an empty folder). We run `func init` to create the project and that command fails if it's not in a venv or if the version is wrong. @qubitron how do you suggest we leverage that setting?

**Comment by brettcannon** [comment]
@EricJizbaMSFT so is the issue that `func init` provides no way to specify the interpreter and so you need to make sure the environment is already activated? Otherwise I'm not quite following what the issue of a workspace setting is as it sounds like it already needs to exist before `func init` runs.

**Comment by brettcannon** [comment]
Right, I remember finding that a bit odd about the Functions CLI the last time I played with it because I believe it then created another directory to put the files into instead of doing it into the current directory as I expected.

So one way to get around this is if you simply send the command to the terminal then the Python extension -- if already running -- will activate any chosen virtual environment automatically in the terminal, so that could be taken care of for you.
