### ISSUE TITLE
Restarting the debugger for a C# project fails

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurefunctions#756]
If you hit the green reconnect button while debugging a C# project:
![screen shot 2018-10-22 at 1 52 13 pm](https://user-images.githubusercontent.com/11282622/47318734-b2549880-d601-11e8-938f-0650cb248729.png)

You will get this error:
"No process with the specified id is currently running."

It's because reconnect uses the same processId even though we've restarted the func host. This isn't a problem in JavaScript or Python since the port stays the same even when the func host has been restarted. I'm honestly not sure how we would fix this. In any case - the user can easily just F5 again.

**Comment by cbrevik** [comment]
I am getting the same error  "No process with the specified id is currently running." when trying to debug on macOS (i.e. when pressing F5, not when restarting debugger).

The steps I take are:
1. Create an empty folder, open it in VS Code.
2. Command: "Azure Functions: Create new project" (C#)
3. Command: "Azure Functions: Create Function" (C#, HttpTrigger).

I don't get this error right away, the first time nothing really happens. But if I reload the VS Code window, then I consistently get this error when trying to debug (F5). The function host is started, and the function is callable. But debugger does not attach. It almost seems like the attach process times out before the function host is finished starting.

The same does not occur if I follow the same steps as above, and select JavaScript instead of C#.

Unclear if this is related to this issue, can open a new issue if needed.

VS Code: 1.30.1
Azure Functions extension: 0.13.1
`dotnet --version`: 2.1.500

**Comment by EricJizbaMSFT** [comment]
Moved @cbrevik's comment to https://github.com/Microsoft/vscode-azurefunctions/issues/894

**Comment by juliusl** [comment]
On windows I don't get a message it just exits the process.
