### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE=1 should be set by default

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#783]
Issue Type: <b>Feature Request</b>

You are using the /zipdeploy endpoint which is good because it enables you to be "running from package" to get the perf benefits, however we only keep as a zip and give those perf benefits [if the app settings "WEBSITE_RUN_FROM_PACKAGE=1" before deploy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#websiterunfrompackage).  It's now going to be the default app setting from VS, makes sense for VS Code to do this as well and should result in better cold start / perf.

Extension version: 0.12.0
VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T12:59:18.833Z)
OS version: Darwin x64 18.2.0

**Comment by EricJizbaMSFT** [comment]
@jeffhollan we already default to `WEBSITE_RUN_FROM_PACKAGE` if the user creates a function app from VS Code. Are you saying you want us to modify existing function apps on deploy?

**Comment by jeffhollan** [comment]
Ah - maybe? I usually create my functions from the portal for whatever reason.  It doesn't hurt to update this from the tooling side after they click the Deploy warning that says you'll overwrite their deployment. This would be consistent with what VS does

**Comment by EricJizbaMSFT** [comment]
> It doesn't hurt

Not so sure about that :P We had C#Script users run into issues with "Run from package" (see https://github.com/Microsoft/vscode-azurefunctions/issues/638). I believe VS only supports C#, but VS Code supports (to varying degrees) almost any language that Azure Functions supports - so it's not as simple.

Can the portal default to WEBSITE_RUN_FROM_PACKAGE? I much prefer using a default because then edge-case users (like C#Script users) can just change the app setting and they're good-to-go. If we dynamically change the setting every time they deploy it gets much more complicated for them to fix.

**Comment by jeffhollan** [comment]
> Can the portal default to WEBSITE_RUN_FROM_PACKAGE

I believe this was being discussed and I think it makes sense.  @btardif do you recall where conversation ended where new sites would be set to run from package by default and only turned OFF if the user turned them off?

**Comment by EricJizbaMSFT** [comment]
Closing as by-design. As mentioned above we already default to this for new apps and we don't want to modify existing function apps.
