### ISSUE TITLE
Issue publishing function

### ISSUE THREAD

**Issue by bpware** [Microsoft/vscode-azurefunctions#852]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy. Pre-deploy task "installExtensions" failed with exit code "127".

Version: 0.13.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@bpware are you just using Http and timer triggers? If so you can probably remove `installExtensions` as a preDeployTask from your settings.json or tasks.json. Let me know if you have any issues doing that.

If you have triggers of different types (blob, queue, etc.) you will need to check the output of `installExtensions` and fix any errors otherwise those won't work
