### ISSUE TITLE
unable to spy variables when debugging 

### ISSUE THREAD

**Issue by b3b00** [Microsoft/vscode-azurefunctions#863]
Hello,

I started using VS Code + azure functions. Works well except when debugging locally. breakpoints are working well but I can't get any value for variables.
I get an error message in the spy panel "internal erro in the C# compiler"

Dont know if its the right place to post. I use VSCode for other projects (console and asp.net) and have no issue with variable spy.

here is my launch.json : 
``{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to C# Functions",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:azureFunctions.pickProcess}"
    }
  ]
}
``

and a screenshot of the spy panel : 
![image](https://user-images.githubusercontent.com/1224790/50013309-191e7e80-ffc1-11e8-99fb-c640bf4fe441.png)

**Comment by b3b00** [comment]
1. it is a  C# (cs files) project
2. func --version returns 2.3.148
3. windows 10
4. VS extensions : 
     - azure functions : v0.31.1
     - azure tools 0.0.5
     -omnisharp C# 1.17.1

**Comment by EricJizbaMSFT** [comment]
@b3b00 sorry for the delayed response. I'm not sure how to help you with this. If you're able to hit breakpoints then I'm guessing there isn't a bug in the functions extension. If you have the code on GitHub I can try to clone and reproduce the bug, otherwise I would suggest filing an issue on the C# debugger extension and maybe they can help: https://github.com/OmniSharp/omnisharp-vscode
