### ISSUE TITLE
Debugging a JavaScript project causes an error

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#873]
**OS:** Windows/Linux
**Node.js:** V10.13.0
**Build Number:** [20181218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1615)

**Repro Steps:**
1. Create a new project with JavaScript.
2. Create a Function adding an HttpTrigger.
3. Debug the project then check the result.

**Expected:**
Succeed to debug with no error.

**Actual:**
There is an error '_The specified task cannot be tracked_'.
![debug](https://user-images.githubusercontent.com/34729022/50141248-fe5e4980-02e1-11e9-87d1-97fc50905e8f.png)

**More info:**
Pop up the below error dialog after clicking 'Debug Anyway'.
![image](https://user-images.githubusercontent.com/34729022/50143803-88111580-02e8-11e9-83b5-e3bd23829810.png)

**Comment by EricJizbaMSFT** [comment]
There are two ways I know of that this could happen:
1. There was a bug in VS Code Insiders about a week ago. What version of insiders are you on? See my comment here https://github.com/Microsoft/vscode-azurefunctions/issues/850#issuecomment-444991064
1. I can repro if I don't have the func cli installed. Do you have it installed? This is already tracked by #328 or #358 (although I increased the priority on 328 since this came up again)

Marking this as duplicate - but waiting to close until I hear back about how you got into this situation

**Comment by v-xuanzh** [comment]
Hi @EricJizbaMSFT , 
1. Details info about the Insider:
Version: 1.31.0-insider (user setup)
Commit: d85a16f2e4354f2850b4171f84fe0c94b0cea338
Date: 2018-12-18T06:20:40.432Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
2. I have installed the func cli with the below version.
![image](https://user-images.githubusercontent.com/34729022/50194044-1f6f7a80-0374-11e9-8bfb-ddc29ba936a2.png)

**Comment by EricJizbaMSFT** [comment]
I'm still not exactly sure how to repro this, but we're refactoring the debug structure as a part of https://github.com/Microsoft/vscode-azurefunctions/issues/822 anyways. I've also listed a few bugs in VS Code in that issue that can cause "The specified task cannot be tracked". Therefore, closing this in favor of #822.
