### ISSUE TITLE
Display 'Function host is not running' after running 'curl <Function Url of WarmUp>'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#952]
**OS:** Mac/Windows
**Node.js:** V 10.15.0
**Build Version**:[20190201.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2674)

**Repro Steps:**
1. Create a Python project with HTTP trigger template and Function level.
2. F5 --> Deploy --> Copy the Url of WarmUp.
3. Check the result.

**Expect:**
'curl "Function Url of WarmUp"' runs well.

**Actual:**
Display 'Function host is not running'.
![image](https://user-images.githubusercontent.com/34729092/52162240-bcb51280-2685-11e9-94ac-06a7c74f9021.png)

**More Info:**
1. Still display '"function name"(Invalid)'.
2. This issue reproduces on Mac and Windows.

**Comment by EricJizbaMSFT** [comment]
@v-dantch it's been a while since you originally filed this bug - but do you remember if you created the "Warmup" function or if it was just there? We had a separate bug here: https://github.com/Microsoft/vscode-azurefunctions/issues/668 because WarmUp is _not_ supposed to show up by default. And I think that was already fixed in the platform.

For the other function (HttpTriggerPY), ServiceUnavailable unfortunately happens sometimes. For windows function apps we can stream logs and sometimes see if there's an error preventing the host from starting, but we can't do that for linux preview. If this happens consistently for you let us know, otherwise I think we'll close this as "external"
