### ISSUE TITLE
The requested app service plan cannot be created in the current resource group because it is hosting Linux apps.

### ISSUE THREAD

**Issue by ikendall** [Microsoft/vscode-azurefunctions#974]
Trying to deploy a Python function to an Azure function app from VS Code (following instructions on https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code). Having done it successfully once, I am now getting an error "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one."

BUT ... the resource group I choose is the same one I was successful at deploying a previous Python function to ... Python functions must always be Linux, as not supported on Windows (yet).

Version: 1.31.0 (User)
OS: winNT x64
Node.js 10.2.0

**Comment by EricJizbaMSFT** [comment]
@ikendall can you verify the resource group in the portal? And check if it has a linux plan or windows plan?

VS Code by default will pick either "Linux" or "Windows" if you create a function app, but it chooses based on your current settings (specifically `azureFunctions.projectLanguage`). If you created the function app with a different workspace open, we might've created a Windows function app since we didn't see those settings.

All that being said, we added a new setting `azureFunctions.advancedCreation` that will _always_ prompt for OS and runtime when creating a function app, so that you can avoid situations like the above. This was tracked by https://github.com/Microsoft/vscode-azurefunctions/issues/811 and will be released soon.

**Comment by ikendall** [comment]
I've deleted it now and moved on, but pretty sure it was Linux (I'd used the same RG to successfully deploy a Python function previously). I installed Azure Functions 0.13.2-alpha in to VSCode as a .visx, and that worked fine ... and a prompt for OS on creating sounds like the right permanent fix. Ticket can be closed. Thank you.
