### ISSUE TITLE
Improve AzureWebJobsStorage experience for local debugging

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurefunctions#976]
When I create a Cosmos trigger I'm asked a bunch of quick pick questions about the Cosmos database, collection, lease, etc.  

Then, I'm prompted in the lower right to select a Storage account to be set in `local.settings.json` for local debugging. 

![image](https://user-images.githubusercontent.com/1487073/52460609-04251e00-2b20-11e9-9f03-8b2348007169.png)

And when i choose "Set Storage Account" I'm sent back up to the quick pick lists.

Why does this prompt show up in the lower right instead of in the quick pick flow at the top/center?

**Comment by EricJizbaMSFT** [comment]
Well...when this prompt was created the prompts _were_ at the top instead of as notifications in the bottom right 😂

Honestly I think we should have a larger discussion around this message. It's been there for a long time, but it's always been a little confusing. I don't think moving to a quick pick will solve that entirely. For example, here are a few things I think we could do:
1. If on Windows and storage emulator is installed, use that and don't prompt
    1. Question: Should we prompt users to install the emulator if it's not installed or keep using storage accounts in Azure as the default?
    1. Note to self: Need to check if the error makes sense if the emulator is installed, but not running
1. If `AzureWebJobsStorage` exists as an environment variable on the system, don't prompt. (Honestly this is what I usually do. It's so much easier to set this once per system instead of once per project)
    1. Note to self: Need to validate the connection string? Not sure if people will set and forget an environment variable and then be confused if they delete that account
1. Prompt right before debugging instead of after function creation. I was hesitant to make this a "required" dialog in the past (hence the "Skip for now" button)  because (a) you have other options as listed above and (b) you don't need it to deploy. But it seems much more reasonable to be "required" right before you debug

**Comment by chrisdias** [comment]
I honestly have no idea why I'm being prompted for a storage account just for debugging :). Is there some way to make it all go away?

**Comment by EricJizbaMSFT** [comment]
At the end of the day that's a question for the platform team. The current solution to "make it all go away" is to use the storage emulator, but that's only available on Windows.

Running the functions runtime locally is the same as running it in the cloud - which I always thought was one of its selling points. So if the platform needs Azure Storage when running in the cloud, it makes sense to me if it needs it locally. But again this is just my understanding and it'd be better to ask someone on the platform team

**Comment by EricJizbaMSFT** [comment]
_originally filed by @gbowerman [here](https://github.com/Azure/azure-functions-python-worker/issues/338)_

Azure Functions VS Code extension 0.14.0.
VS Code 1.31.1.
Windows 10.

Create Azure Function, select Timer Trigger.
In side by side tests, on Mac this prompted user for a storage account, on Windows it didn't.

Subsequently running function locally fails due to AzureWebJobsStorage not set.

**Comment by EricJizbaMSFT** [comment]
Per @jinglouMSFT storage emulator also has a cross plat thing: https://github.com/Azure/Azurite
